In [1]:
!pip install pyspark

Requirement already satisfied: pyspark in /usr/local/lib/python3.13/dist-packages (4.0.4)
Requirement already satisfied: py4j<0.10.9.10,>=0.10.9.7 in /usr/local/lib/python3.13/dist-packages (from pyspark) (0.10.9.9)

In [2]:
from pyspark.sql import SparkSession

spark = SparkSession.builder \
.appName("PySpark Training") \
.getOrCreate()

In [3]:
from google.colab import files
uploaded = files.upload()

Saving plant_master.csv to plant_master.csv
Saving manufacturing_production_120k.csv to manufacturing_production_120k.csv
Saving manufacturing_production_extra_12k.csv to manufacturing_production_extra_12k.csv
Saving machine_master.csv to machine_master.csv
Saving machine_configurations.json to machine_configurations.json

In [4]:
df = spark.read.csv(
  "manufacturing_production_120k.csv",
  header=True,
  inferSchema=True
)

Load the Data in PySpark:

  1. Display first 20 rows.
  2. Display schema.
  3. Display column names.
  4. Count total records.
  5. Display only production ID, plant, machine, product family and units produced.
  6. Check the datatype of each column.
  7. Display 10 random-looking sample records using sample().

In [5]:
df.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

In [6]:
df.printSchema()

root
 |-- production_id: string (nullable = true)
 |-- production_date: date (nullable = true)
 |-- plant_id: string (nullable = true)
 |-- machine_id: string (nullable = true)
 |-- operator_id: string (nullable = true)
 |-- shift: string (nullable = true)
 |-- product_code: string (nullable = true)
 |-- product_family: string (nullable = true)
 |-- units_planned: integer (nullable = true)
 |-- units_produced: integer (nullable = true)
 |-- defective_units: integer (nullable = true)
 |-- downtime_minutes: integer (nullable = true)
 |-- energy_kwh: double (nullable = true)
 |-- temperature_c: double (nullable = true)
 |-- vibration_mm_s: double (nullable = true)
 |-- quality_status: string (nullable = true)
 |-- maintenance_flag: string (nullable = true)
 |-- supervisor: string (nullable = true)

In [7]:
print(df.columns)

['production_id', 'production_date', 'plant_id', 'machine_id', 'operator_id', 'shift', 'product_code', 'product_family', 'units_planned', 'units_produced', 'defective_units', 'downtime_minutes', 'energy_kwh', 'temperature_c', 'vibration_mm_s', 'quality_status', 'maintenance_flag', 'supervisor']

In [8]:
print("Total Records: ", df.count())

Total Records:  120000

In [9]:
print(df.dtypes)

[('production_id', 'string'), ('production_date', 'date'), ('plant_id', 'string'), ('machine_id', 'string'), ('operator_id', 'string'), ('shift', 'string'), ('product_code', 'string'), ('product_family', 'string'), ('units_planned', 'int'), ('units_produced', 'int'), ('defective_units', 'int'), ('downtime_minutes', 'int'), ('energy_kwh', 'double'), ('temperature_c', 'double'), ('vibration_mm_s', 'double'), ('quality_status', 'string'), ('maintenance_flag', 'string'), ('supervisor', 'string')]

In [10]:
df.select("production_id", "plant_id", "machine_id", "product_family", "units_produced").show()

+-------------+--------+----------+--------------+--------------+
|production_id|plant_id|machine_id|product_family|units_produced|
+-------------+--------+----------+--------------+--------------+
|    PR0000001|    PL03|     MC011|        Motors|           993|
|    PR0000002|    PL04|     MC019|   Controllers|           836|
|    PR0000003|    PL01|     MC002|        Motors|           380|
|    PR0000004|    PL03|     MC013|         Pumps|           720|
|    PR0000005|    PL04|     MC020|         Pumps|           296|
|    PR0000006|    PL01|     MC002|        Motors|           795|
|    PR0000007|    PL02|     MC007|        Valves|           955|
|    PR0000008|    PL02|     MC009|        Valves|           895|
|    PR0000009|    PL03|     MC015|   Controllers|           289|
|    PR0000010|    PL02|     MC006|   Controllers|           527|
|    PR0000011|    PL03|     MC012|         Pumps|           512|
|    PR0000012|    PL06|     MC030|   Controllers|           968|
|    PR0000013|    PL06|     MC027|   Controllers|           867|
|    PR0000014|    PL03|     MC013|        Valves|           456|
|    PR0000015|    PL02|     MC007|        Motors|          1042|
|    PR0000016|    PL04|     MC020|   Controllers|           732|
|    PR0000017|    PL03|     MC011|   Controllers|           963|
|    PR0000018|    PL03|     MC012|        Motors|           469|
|    PR0000019|    PL01|     MC005|        Valves|           380|
|    PR0000020|    PL03|     MC014|         Pumps|           573|
+-------------+--------+----------+--------------+--------------+
only showing top 20 rows

In [11]:
df.sample(withReplacement=False, fraction=0.1, seed=42).limit(10).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|
|    PR0000051|     2026-06-12|    PL05|     MC021|     OP0337|Morning|     PMP-310|         Pumps|          960|           975|             17|              51|    380.84|        72.08|          3.59|          Pass|              No|    Bharat|
|    PR0000059|     2026-09-27|    PL04|     MC018|     OP0276|Morning|     PMP-110|         Pumps|          922|           952|             49|              17|    265.29|        58.28|          4.41|        Reject|              No|    Charan|
|    PR0000064|     2026-10-21|    PL05|     MC022|     OP0267|Evening|     CTL-230|   Controllers|          805|           794|             16|              38|    189.94|        76.15|          3.55|          Pass|              No|     Anita|
|    PR0000067|     2026-05-08|    PL05|     MC022|     OP0311|Morning|     VLV-320|        Valves|          384|           362|             11|              54|     80.43|        56.44|          4.21|        Reject|              No|     Gopal|
|    PR0000073|     2026-10-16|    PL02|     MC010|     OP0580|Evening|     PMP-210|         Pumps|          973|           979|             13|              13|    475.51|        62.22|          5.32|        Rework|              No|    Harini|
|    PR0000080|     2026-06-10|    PL01|     MC003|     OP0214|  Night|     CTL-130|   Controllers|          948|           821|             49|              20|    188.65|        62.68|          2.85|        Reject|              No|     Anita|
|    PR0000089|     2026-09-20|    PL03|     MC014|     OP0375|  Night|     PMP-210|         Pumps|         1133|           971|             22|              14|    294.73|         NULL|          4.97|        Reject|              No|     Anita|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+

Creating DataFrames:

  Create a small DataFrame manually containing:

plant_id,
plant_name,
city

Then:
1. Create it using a list of tuples.
2. Create it with explicit column names.
3. Create another version using StructType .
4. Print the schema.
5. Add a constant column called country = India .

In [12]:
data = [
    (101, "Alpha Plant", "Mumbai"),
    (102, "Beta Refineries", "Bengaluru"),
    (103, "Gamma Manufacturing", "Chennai")
]


columns = ["plant_id", "plant_name", "city"]


df_tuples = spark.createDataFrame(data, columns)
df_tuples.show()

+--------+-------------------+---------+
|plant_id|         plant_name|     city|
+--------+-------------------+---------+
|     101|        Alpha Plant|   Mumbai|
|     102|    Beta Refineries|Bengaluru|
|     103|Gamma Manufacturing|  Chennai|
+--------+-------------------+---------+

In [13]:
from pyspark.sql.types import StructType, StructField, IntegerType, StringType

schema = StructType([
    StructField("plant_id", IntegerType(), True),
    StructField("plant_name", StringType(), True),
    StructField("city", StringType(), True)
])


df_struct = spark.createDataFrame(data, schema)
df_struct.show()

+--------+-------------------+---------+
|plant_id|         plant_name|     city|
+--------+-------------------+---------+
|     101|        Alpha Plant|   Mumbai|
|     102|    Beta Refineries|Bengaluru|
|     103|Gamma Manufacturing|  Chennai|
+--------+-------------------+---------+

In [14]:
df_struct.printSchema()

root
 |-- plant_id: integer (nullable = true)
 |-- plant_name: string (nullable = true)
 |-- city: string (nullable = true)

In [15]:
from pyspark.sql.functions import lit

df_final = df_struct.withColumn("country", lit("India"))

df_final.show()

+--------+-------------------+---------+-------+
|plant_id|         plant_name|     city|country|
+--------+-------------------+---------+-------+
|     101|        Alpha Plant|   Mumbai|  India|
|     102|    Beta Refineries|Bengaluru|  India|
|     103|Gamma Manufacturing|  Chennai|  India|
+--------+-------------------+---------+-------+

Pandas DataFrame:

1. Display first 5 rows.
2. Display last 5 rows.
3. Display shape.
4. Display column names.
5. Display datatypes.
6. Select plant_id , machine_id , units_produced .
7. Rename units_produced to production_output .
8. Filter rows where quality_status == "Reject" .
9. Filter rows where temperature is greater than 75.
10. Filter Night-shift production from Hyderabad plant.

In [16]:
import pandas as pd
pdf = pd.read_csv("manufacturing_production_120k.csv")

In [17]:
pdf.head(5)

,production_id,production_date,plant_id,machine_id,operator_id,shift,product_code,product_family,units_planned,units_produced,defective_units,downtime_minutes,energy_kwh,temperature_c,vibration_mm_s,quality_status,maintenance_flag,supervisor
0,PR0000001,2026-08-07,PL03,MC011,OP0275,Evening,MTR-100,Motors,1060,993,30,34.0,388.11,61.40,3.88,Rework,No,Charan
1,PR0000002,2026-08-03,PL04,MC019,OP0489,Morning,CTL-330,Controllers,809,836,0,0.0,398.58,64.37,2.28,Reject,No,Farah
2,PR0000003,2026-05-20,PL01,MC002,OP0189,Evening,MTR-300,Motors,442,380,17,15.0,183.34,54.13,4.66,Reject,No,Deepa
3,PR0000004,2026-01-15,PL03,MC013,OP0076,Morning,PMP-210,Pumps,787,720,7,39.0,217.61,64.47,NaN,Rework,No,Farah
4,PR0000005,2026-09-21,PL04,MC020,OP0501,Morning,PMP-110,Pumps,344,296,7,49.0,115.47,72.59,3.21,Pass,No,Deepa

In [18]:
pdf.tail(5)

,production_id,production_date,plant_id,machine_id,operator_id,shift,product_code,product_family,units_planned,units_produced,defective_units,downtime_minutes,energy_kwh,temperature_c,vibration_mm_s,quality_status,maintenance_flag,supervisor
119995,PR0119996,2026-07-13,PL05,MC022,OP0193,Evening,MTR-200,Motors,435,399,1,73.0,126.07,62.79,5.73,Rework,No,Bharat
119996,PR0119997,2026-04-26,PL05,MC024,OP0124,Evening,CTL-130,Controllers,813,777,8,49.0,318.22,63.05,3.53,Pass,No,Irfan
119997,PR0119998,2026-02-01,PL06,MC027,OP0051,Evening,VLV-120,Valves,650,597,13,0.0,269.46,60.52,3.81,Pass,No,Bharat
119998,PR0119999,2026-01-17,PL01,MC001,OP0452,Evening,MTR-300,Motors,887,899,22,21.0,184.62,64.89,5.20,Pass,Yes,Farah
119999,PR0120000,2026-08-16,PL02,MC007,OP0420,Morning,MTR-200,Motors,547,477,4,43.0,107.95,62.50,3.97,Pass,No,Farah

In [19]:
print(pdf.shape)

(120000, 18)

In [20]:
print(pdf.columns)

Index(['production_id', 'production_date', 'plant_id', 'machine_id',
       'operator_id', 'shift', 'product_code', 'product_family',
       'units_planned', 'units_produced', 'defective_units',
       'downtime_minutes', 'energy_kwh', 'temperature_c', 'vibration_mm_s',
       'quality_status', 'maintenance_flag', 'supervisor'],
      dtype='object')

In [21]:
print(pdf.dtypes)

production_id        object
production_date      object
plant_id             object
machine_id           object
operator_id          object
shift                object
product_code         object
product_family       object
units_planned         int64
units_produced        int64
defective_units       int64
downtime_minutes    float64
energy_kwh          float64
temperature_c       float64
vibration_mm_s      float64
quality_status       object
maintenance_flag     object
supervisor           object
dtype: object

In [22]:
pdf_subset = pdf[["plant_id", "machine_id", "units_produced"]]
pdf_subset.head()

  plant_id machine_id  units_produced
0     PL03      MC011             993
1     PL04      MC019             836
2     PL01      MC002             380
3     PL03      MC013             720
4     PL04      MC020             296

In [23]:
pdf.rename(columns={"units_produced": "production_output"}, inplace=True)

In [24]:
rejects_df = pdf[pdf["quality_status"] == "Reject"]
rejects_df.head()

,production_id,production_date,plant_id,machine_id,operator_id,shift,product_code,product_family,units_planned,production_output,defective_units,downtime_minutes,energy_kwh,temperature_c,vibration_mm_s,quality_status,maintenance_flag,supervisor
1,PR0000002,2026-08-03,PL04,MC019,OP0489,Morning,CTL-330,Controllers,809,836,0,0.0,398.58,64.37,2.28,Reject,No,Farah
2,PR0000003,2026-05-20,PL01,MC002,OP0189,Evening,MTR-300,Motors,442,380,17,15.0,183.34,54.13,4.66,Reject,No,Deepa
7,PR0000008,2026-08-17,PL02,MC009,OP0106,Night,VLV-320,Valves,862,895,51,77.0,266.06,57.10,1.34,Reject,No,Irfan
9,PR0000010,2026-02-13,PL02,MC006,OP0593,Evening,CTL-230,Controllers,532,527,26,64.0,112.17,60.96,3.48,Reject,No,Gopal
21,PR0000022,2026-03-03,PL02,MC009,OP0294,Evening,MTR-300,Motors,623,560,23,14.0,217.69,55.23,3.28,Reject,Yes,Farah

In [25]:
high_temp_df = pdf[pdf["temperature_c"] > 75]
high_temp_df.head()

,production_id,production_date,plant_id,machine_id,operator_id,shift,product_code,product_family,units_planned,production_output,defective_units,downtime_minutes,energy_kwh,temperature_c,vibration_mm_s,quality_status,maintenance_flag,supervisor
14,PR0000015,2026-03-15,PL02,MC007,OP0238,Morning,MTR-300,Motors,1086,1042,4,172.0,239.64,76.39,2.81,Pass,No,Deepa
16,PR0000017,2026-08-04,PL03,MC011,OP0533,Morning,CTL-330,Controllers,1152,963,28,91.0,347.34,75.09,4.00,Pass,Yes,Gopal
19,PR0000020,2026-02-18,PL03,MC014,OP0563,Morning,PMP-310,Pumps,646,573,13,64.0,277.73,76.92,2.35,Pass,No,Irfan
26,PR0000027,2026-01-03,PL05,MC023,OP0190,Morning,PMP-210,Pumps,358,310,6,46.0,78.29,75.42,3.72,Rework,No,Anita
54,PR0000055,2026-07-31,PL01,MC005,OP0212,Morning,CTL-230,Controllers,499,478,10,32.0,112.60,75.10,3.38,Pass,No,Farah

In [26]:
night_hyd_df = pdf[(pdf["shift"] == "Night") & (pdf["plant_id"] == "PL01")]
night_hyd_df.head()

,production_id,production_date,plant_id,machine_id,operator_id,shift,product_code,product_family,units_planned,production_output,defective_units,downtime_minutes,energy_kwh,temperature_c,vibration_mm_s,quality_status,maintenance_flag,supervisor
29,PR0000030,2026-09-18,PL01,MC004,OP0266,Night,VLV-320,Valves,358,359,1,19.0,107.98,72.00,1.73,Pass,No,Bharat
38,PR0000039,2026-07-17,PL01,MC002,OP0220,Night,VLV-120,Valves,260,265,0,2.0,127.18,51.87,3.41,Pass,No,Irfan
62,PR0000063,2026-02-18,PL01,MC002,OP0390,Night,VLV-120,Valves,656,665,0,44.0,311.80,58.34,2.00,Pass,No,Deepa
79,PR0000080,2026-06-10,PL01,MC003,OP0214,Night,CTL-130,Controllers,948,821,49,20.0,188.65,62.68,2.85,Reject,No,Anita
145,PR0000146,2026-08-19,PL01,MC005,OP0088,Night,VLV-120,Valves,1156,969,0,9.0,501.65,67.41,5.76,Rework,No,Bharat

Dask DataFrame:

1. Display first records using head() .
2. Find number of partitions.
3. Select plant_id , product_family , units_produced .
4. Filter rejected production records.
5. Calculate average units produced by plant.
6. Calculate total defects by product family.
7. Use .compute() to obtain the final result.
8. Compare doing the same aggregation in Pandas and Dask.

In [27]:
import dask.dataframe as dd

manufacturing_dtypes = {
    'production_id': 'object',
    'production_date': 'object',
    'plant_id': 'object',
    'machine_id': 'object',
    'operator_id': 'object',
    'shift': 'object',
    'product_code': 'object',
    'product_family': 'object',
    'units_planned': 'int64',
    'units_produced': 'int64',
    'defective_units': 'int64',
    'downtime_minutes': 'float64',
    'energy_kwh': 'float64',
    'temperature_c': 'float64',
    'vibration_mm_s': 'float64',
    'quality_status': 'object',
    'maintenance_flag': 'object',
    'supervisor': 'object'
}

ddf = dd.read_csv(
  "manufacturing_production_120k.csv", dtype = manufacturing_dtypes
)

In [28]:
ddf.head()

,production_id,production_date,plant_id,machine_id,operator_id,shift,product_code,product_family,units_planned,units_produced,defective_units,downtime_minutes,energy_kwh,temperature_c,vibration_mm_s,quality_status,maintenance_flag,supervisor
0,PR0000001,2026-08-07,PL03,MC011,OP0275,Evening,MTR-100,Motors,1060,993,30,34.0,388.11,61.40,3.88,Rework,No,Charan
1,PR0000002,2026-08-03,PL04,MC019,OP0489,Morning,CTL-330,Controllers,809,836,0,0.0,398.58,64.37,2.28,Reject,No,Farah
2,PR0000003,2026-05-20,PL01,MC002,OP0189,Evening,MTR-300,Motors,442,380,17,15.0,183.34,54.13,4.66,Reject,No,Deepa
3,PR0000004,2026-01-15,PL03,MC013,OP0076,Morning,PMP-210,Pumps,787,720,7,39.0,217.61,64.47,NaN,Rework,No,Farah
4,PR0000005,2026-09-21,PL04,MC020,OP0501,Morning,PMP-110,Pumps,344,296,7,49.0,115.47,72.59,3.21,Pass,No,Deepa

In [29]:
print(f"Number of partitions: {ddf.npartitions}")

Number of partitions: 1

In [30]:
df_subset = ddf[["plant_id", "product_family", "units_produced"]]
df_subset.head()

  plant_id product_family  units_produced
0     PL03         Motors             993
1     PL04    Controllers             836
2     PL01         Motors             380
3     PL03          Pumps             720
4     PL04          Pumps             296

In [31]:
rejected_ddf = ddf[ddf["quality_status"] == "Reject"]
rejected_ddf.head()

,production_id,production_date,plant_id,machine_id,operator_id,shift,product_code,product_family,units_planned,units_produced,defective_units,downtime_minutes,energy_kwh,temperature_c,vibration_mm_s,quality_status,maintenance_flag,supervisor
1,PR0000002,2026-08-03,PL04,MC019,OP0489,Morning,CTL-330,Controllers,809,836,0,0.0,398.58,64.37,2.28,Reject,No,Farah
2,PR0000003,2026-05-20,PL01,MC002,OP0189,Evening,MTR-300,Motors,442,380,17,15.0,183.34,54.13,4.66,Reject,No,Deepa
7,PR0000008,2026-08-17,PL02,MC009,OP0106,Night,VLV-320,Valves,862,895,51,77.0,266.06,57.10,1.34,Reject,No,Irfan
9,PR0000010,2026-02-13,PL02,MC006,OP0593,Evening,CTL-230,Controllers,532,527,26,64.0,112.17,60.96,3.48,Reject,No,Gopal
21,PR0000022,2026-03-03,PL02,MC009,OP0294,Evening,MTR-300,Motors,623,560,23,14.0,217.69,55.23,3.28,Reject,Yes,Farah

In [32]:
avg_units_by_plant = ddf.groupby("plant_id")["units_produced"].mean()

final_avg_units = avg_units_by_plant.compute()
print(final_avg_units)

plant_id
PL01    672.998304
PL02    672.781326
PL03    675.665503
PL04    673.835101
PL05    673.124994
PL06    678.006884
Name: units_produced, dtype: float64

In [33]:
total_defects_by_family = ddf.groupby("product_family")["defective_units"].sum()

final_defects = total_defects_by_family.compute()
print(final_defects)

product_family
Controllers    507781
Motors         505287
Pumps          507864
Valves         509312
Name: defective_units, dtype: int64

In [34]:
# Pandas
pdf.groupby("plant_id")["production_output"].mean() # Eager, Single Threaded, Limited to RAM

# Dask
ddf.groupby("plant_id")["units_produced"].mean().compute() # Lazy, Parallelism, Can handle datasets larger than memory

plant_id
PL01    672.998304
PL02    672.781326
PL03    675.665503
PL04    673.835101
PL05    673.124994
PL06    678.006884
Name: units_produced, dtype: float64

Manipulating DataFrames:

1. Create:

    production_efficiency = units_produced / units_planned * 100

2. Create:

    good_units = units_produced - defective_units

3. Add:

    country = India

4. Rename energy_kwh to energy_consumed .
5. Convert units_produced to double.
6. Create defect_percentage .
7. Create energy_per_unit .
8. Select only the transformed columns.

In [35]:
from pyspark.sql.functions import col, lit
from pyspark.sql.types import DoubleType

In [36]:
df_mod = df.withColumn("production_efficiency", (col("units_produced") / col("units_planned")) * 100)

In [37]:
df_mod = df_mod.withColumn("good_units", col("units_produced") - col("defective_units"))

In [38]:
df_mod = df_mod.withColumn("country", lit("India"))

In [39]:
df_mod = df_mod.withColumnRenamed("energy_kwh", "energy_consumed")

In [40]:
df_mod = df_mod.withColumn("units_produced", col("units_produced").cast(DoubleType()))

In [41]:
df_mod = df_mod.withColumn("defect_percentage", (col("defective_units") / col("units_produced")) * 100)

In [42]:
df_mod = df_mod.withColumn("energy_per_unit", col("energy_consumed") / col("units_produced"))

In [43]:
transformed_cols = [
    "production_efficiency", "good_units", "country",
    "energy_consumed", "units_produced", "defect_percentage", "energy_per_unit"
]
df_mod.select(*transformed_cols).show()

+---------------------+----------+-------+---------------+--------------+------------------+-------------------+
|production_efficiency|good_units|country|energy_consumed|units_produced| defect_percentage|    energy_per_unit|
+---------------------+----------+-------+---------------+--------------+------------------+-------------------+
|    93.67924528301886|       963|  India|         388.11|         993.0|3.0211480362537766|0.39084592145015107|
|   103.33745364647713|       836|  India|         398.58|         836.0|               0.0| 0.4767703349282296|
|    85.97285067873304|       363|  India|         183.34|         380.0| 4.473684210526316|0.48247368421052633|
|     91.4866581956798|       713|  India|         217.61|         720.0|0.9722222222222222|0.30223611111111115|
|    86.04651162790698|       289|  India|         115.47|         296.0| 2.364864864864865| 0.3901013513513513|
|    82.98538622129436|       745|  India|         290.26|         795.0| 6.289308176100629| 0.3651069182389937|
|    81.97424892703863|       945|  India|         355.56|         955.0|1.0471204188481675|0.37231413612565445|
|   103.82830626450117|       844|  India|         266.06|         895.0| 5.698324022346369| 0.2972737430167598|
|    92.33226837060703|       281|  India|          87.62|         289.0| 2.768166089965398| 0.3031833910034602|
|    99.06015037593986|       501|  India|         112.17|         527.0| 4.933586337760911| 0.2128462998102467|
|    88.73483535528595|       498|  India|          127.0|         512.0|          2.734375|        0.248046875|
|    98.77551020408163|       945|  India|         377.97|         968.0|  2.37603305785124| 0.3904648760330579|
|    86.35458167330677|       840|  India|         388.61|         867.0|3.1141868512110724| 0.4482237600922722|
|   101.78571428571428|       450|  India|         108.83|         456.0|1.3157894736842104|0.23866228070175438|
|    95.94843462246777|      1038|  India|         239.64|        1042.0|0.3838771593090211|0.22998080614203453|
|    84.13793103448276|       732|  India|         289.55|         732.0|               0.0| 0.3955601092896175|
|             83.59375|       935|  India|         347.34|         963.0| 2.907580477673936|0.36068535825545167|
|    86.69131238447319|       451|  India|         241.05|         469.0|3.8379530916844353| 0.5139658848614073|
|    99.73753280839895|       364|  India|         137.99|         380.0|4.2105263157894735|0.36313157894736847|
|    88.69969040247679|       560|  India|         277.73|         573.0|2.2687609075043627|  0.484694589877836|
+---------------------+----------+-------+---------------+--------------+------------------+-------------------+
only showing top 20 rows

Dropping Data

1. Drop supervisor .
2. Drop supervisor and maintenance_flag .
3. Remove duplicate rows.
4. Keep one record per production_id .
5. Remove records where operator ID is missing.
6. Remove rows where both temperature and vibration are missing.
7. Display unique product families.
8. Display unique plant-machine combinations.

In [44]:
df_cleaned = df.drop("supervisor", "maintenance_flag")

In [45]:
df_cleaned = df_cleaned.dropDuplicates()

In [46]:
df_cleaned = df_cleaned.dropDuplicates(["production_id"])

In [47]:
df_cleaned = df_cleaned.dropna(subset=["operator_id"])

In [48]:
df_cleaned = df_cleaned.dropna(how="all", subset=["temperature_c", "vibration_mm_s"])

In [49]:
df_cleaned.select("product_family").distinct().show()

+--------------+
|product_family|
+--------------+
|         Pumps|
|        Valves|
|   Controllers|
|        Motors|
+--------------+

In [50]:
df_cleaned.select("plant_id", "machine_id").distinct().show()

+--------+----------+
|plant_id|machine_id|
+--------+----------+
|    PL01|     MC001|
|    PL01|     MC004|
|    PL04|     MC019|
|    PL04|     MC017|
|    PL05|     MC022|
|    PL04|     MC018|
|    PL01|     MC003|
|    PL06|     MC029|
|    PL02|     MC007|
|    PL03|     MC013|
|    PL06|     MC030|
|    PL04|     MC020|
|    PL05|     MC021|
|    PL01|     MC005|
|    PL02|     MC010|
|    PL04|     MC016|
|    PL06|     MC027|
|    PL02|     MC006|
|    PL01|     MC002|
|    PL06|     MC028|
+--------+----------+
only showing top 20 rows

In [51]:
df_cleaned.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|
|    PR0000025|     2026-07-28|    PL04|     MC017|     OP0636|Evening|     VLV-220|        Valves|         1139|          1126|             38|              13|    332.97|        58.08|          4.15|          Pass|
|    PR0000026|     2026-04-09|    PL01|     MC001|     OP0604|Evening|     MTR-300|        Motors|          643|           663|             20|              26|    180.36|        63.77|          4.49|          Pass|
|    PR0000031|     2026-01-04|    PL01|     MC003|     OP0524|Evening|     PMP-210|         Pumps|          762|           776|             49|              28|    238.12|         66.8|          3.09|        Reject|
|    PR0000032|     2026-05-28|    PL06|     MC030|     OP0074|  Night|     CTL-230|   Controllers|          819|           773|             11|              27|     354.3|        63.51|          3.18|          Pass|
|    PR0000036|     2026-07-13|    PL04|     MC020|     OP0559|Evening|     MTR-200|        Motors|          576|           578|              0|              38|    267.36|        70.28|          2.69|          Pass|
|    PR0000037|     2026-10-12|    PL06|     MC026|     OP0163|Morning|     MTR-100|        Motors|          633|           626|             15|              56|    173.17|        64.63|           3.7|          Pass|
|    PR0000038|     2026-02-23|    PL02|     MC008|     OP0114|  Night|     MTR-300|        Motors|          864|           867|              6|              38|    335.24|         53.7|           3.0|          Pass|
|    PR0000039|     2026-07-17|    PL01|     MC002|     OP0220|  Night|     VLV-120|        Valves|          260|           265|              0|               2|    127.18|        51.87|          3.41|          Pass|
|    PR0000041|     2026-05-14|    PL02|     MC009|     OP0192|Morning|     PMP-310|         Pumps|          711|           664|             32|              60|    335.84|        57.87|           3.2|          Pass|
|    PR0000046|     2026-04-02|    PL06|     MC027|     OP0484|Morning|     VLV-120|        Valves|          847|           778|             19|             145|    381.88|        63.42|          2.94|        Reject|
|    PR0000047|     2026-01-22|    PL06|     MC028|     OP0512|Evening|     PMP-110|         Pumps|          956|           882|              4|             118|     247.4|         NULL|          2.52|          Pass|
|    PR0000048|     2026-03-08|    PL03|     MC015|     OP0110|Morning|     CTL-230|   Controllers|          858|           810|              0|               0|    250.54|        58.93|          4.04|          Pass|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+
only showing top 20 rows

Sorting:

1. Sort by units produced ascending.
2. Sort units produced descending.
3. Sort highest defective units first.
4. Sort by plant and then production output descending.
5. Display the top 20 production runs.
6. Display the 10 runs with highest downtime.
7. Find machines with the highest recorded vibration.

In [52]:
# df_sorted_asc = df.sort("units_produced")
df.orderBy(col("units_produced").asc()).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0038643|     2026-08-06|    PL02|     MC009|     OP0361|Evening|     MTR-100|        Motors|          250|           205|              6|              73|     65.18|        55.99|          2.72|          Pass|              No|    Harini|
|    PR0059668|     2026-05-01|    PL05|     MC021|     OP0067|  Night|     CTL-130|   Controllers|          250|           205|             11|              54|     89.67|        58.31|          2.69|          Pass|              No|     Anita|
|    PR0079337|     2026-05-05|    PL04|     MC018|     OP0623|Evening|     PMP-210|         Pumps|          251|           206|              0|               0|     77.66|        67.78|          2.36|        Rework|              No|     Irfan|
|    PR0013719|     2026-04-30|    PL03|     MC014|     OP0340|Morning|     MTR-200|        Motors|          250|           206|              5|              82|     62.29|        55.57|           2.4|          Pass|              No|    Harini|
|    PR0087182|     2026-09-03|    PL04|     MC019|     OP0196|Evening|     CTL-330|   Controllers|          250|           206|              4|              13|     98.25|        59.27|          6.99|        Reject|             Yes|     Irfan|
|    PR0015709|     2026-03-09|    PL05|     MC021|     OP0538|  Night|     VLV-220|        Valves|          251|           206|              9|               3|     87.29|        68.35|          1.27|        Reject|              No|    Bharat|
|    PR0115075|     2026-10-03|    PL04|     MC019|     OP0014|  Night|     CTL-130|   Controllers|          251|           206|              1|              66|     79.31|         78.2|          4.21|        Rework|              No|    Bharat|
|    PR0026161|     2026-04-28|    PL05|     MC025|     OP0617|Evening|     PMP-210|         Pumps|          251|           206|              2|              42|     74.72|        76.08|          3.96|        Reject|             Yes|     Gopal|
|    PR0030899|     2026-05-24|    PL01|     MC004|     OP0380|Evening|     VLV-120|        Valves|          252|           206|             12|              12|     75.94|        50.77|          3.34|        Rework|              No|     Farah|
|    PR0039880|     2026-01-04|    PL01|     MC005|     OP0034|Evening|     PMP-210|         Pumps|          250|           206|              0|              38|      50.0|        64.38|          2.33|        Rework|              No|     Deepa|
|    PR0071924|     2026-05-26|    PL01|     MC003|     OP0120|  Night|     PMP-210|         Pumps|          251|           206|              9|              40|      50.0|        52.13|          2.54|          Pass|              No|     Irfan|
|    PR0107410|     2026-09-29|    PL03|     MC012|     OP0237|Evening|     VLV-120|        Valves|          252|           207|              8|              36|     99.97|        61.39|          3.94|          Pass|              No|     Deepa|
|    PR0013195|     2026-03-18|    PL05|     MC021|     OP0182|  Night|     PMP-310|         Pumps|          253|           207|              4|              18|     59.88|        73.69|          2.98|          Pass|              No|     Irfan|
|    PR0118888|     2026-06-01|    PL04|     MC019|     OP0350|Morning|     MTR-300|        Motors|          250|           207|              3|              29|      50.0|        53.55|          4.18|          Pass|              No|     Farah|
|    PR0020293|     2026-08-08|    PL03|     MC014|     OP0567|Evening|     CTL-130|   Controllers|          253|           207|              5|              37|      50.0|        64.89|          1.81|          Pass|              No|     Deepa|
|    PR0028542|     2026-04-10|    PL04|     MC020|     OP0325|Evening|     CTL-230|   Controllers|          251|           207|              8|              18|     93.84|         64.9|          1.55|          Pass|              No|     Anita|
|    PR0035230|     2026-02-05|    PL06|     MC029|     OP0479|  Night|     VLV-120|        Valves|          253|           207|              6|               0|    107.62|         NULL|          3.56|        Rework|              No|     Anita|
|    PR0097162|     2026-09-02|    PL06|     MC027|     OP0139|  Night|     MTR-100|        Motors|          252|           208|              6|              11|     92.62|        61.86|          1.74|          Pass|              No|     Deepa|
|    PR0005895|     2026-09-15|    PL04|     MC018|     OP0322|  Night|     VLV-320|        Valves|          251|           208|              3|              33|     66.87|        49.32|          2.91|          Pass|              No|    Bharat|
|    PR0105232|     2026-08-26|    PL04|     MC018|     OP0505|Evening|     VLV-220|        Valves|          251|           208|              8|               0|      59.1|        57.55|          3.65|          Pass|              No|     Irfan|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

In [53]:
df.orderBy(col("units_produced").desc()).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0087560|     2026-06-29|    PL04|     MC018|     OP0587|  Night|     VLV-120|        Valves|         1199|          1245|             60|               0|    500.87|        58.11|          3.58|          Pass|             Yes|    Charan|
|    PR0008535|     2026-02-23|    PL04|     MC018|     OP0286|Morning|     MTR-200|        Motors|         1199|          1245|              0|              53|    257.72|        60.24|           2.6|          Pass|              No|     Farah|
|    PR0100473|     2026-10-18|    PL02|     MC009|     OP0559|  Night|     CTL-230|   Controllers|         1198|          1245|             53|              16|    375.27|         58.3|          2.82|        Reject|              No|     Irfan|
|    PR0098612|     2026-09-02|    PL05|     MC024|     OP0268|Morning|     PMP-210|         Pumps|         1199|          1245|             23|               0|    350.65|        56.41|          2.13|          Pass|              No|    Bharat|
|    PR0010732|     2026-09-26|    PL02|     MC007|     OP0496|Evening|     PMP-210|         Pumps|         1200|          1243|              0|               0|    599.61|        75.16|           1.8|          Pass|              No|     Gopal|
|    PR0082579|     2026-01-20|    PL03|     MC013|     OP0313|Morning|     MTR-100|        Motors|         1200|          1243|              1|              40|    517.17|        51.05|          3.65|        Rework|              No|    Charan|
|    PR0047939|     2026-09-28|    PL04|     MC020|     OP0174|Evening|     PMP-210|         Pumps|         1199|          1243|             42|              28|    502.25|        66.71|          2.97|          Pass|              No|     Anita|
|    PR0001765|     2026-09-15|    PL02|     MC006|     OP0088|  Night|     MTR-300|        Motors|         1195|          1242|              0|               0|    303.92|        58.93|          4.05|        Reject|             Yes|     Deepa|
|    PR0069661|     2026-01-28|    PL04|     MC020|     OP0499|Evening|     CTL-130|   Controllers|         1200|          1242|             13|              40|     392.3|         NULL|           2.7|          Pass|             Yes|     Irfan|
|    PR0064142|     2026-01-10|    PL06|     MC028|     OP0332|Morning|     PMP-310|         Pumps|         1195|          1241|             39|              41|    547.34|        77.31|          3.18|          Pass|              No|    Harini|
|    PR0116814|     2026-04-16|    PL05|     MC022|     OP0125|Evening|     CTL-130|   Controllers|         1200|          1240|             22|              50|    515.01|        68.24|          3.18|          Pass|              No|    Charan|
|    PR0030298|     2026-05-04|    PL03|     MC011|     OP0514|  Night|     CTL-130|   Controllers|         1195|          1239|             30|              74|    616.84|        60.83|          5.16|          Pass|              No|    Harini|
|    PR0093782|     2026-06-01|    PL04|     MC020|     OP0240|Evening|     VLV-320|        Valves|         1192|          1239|             10|               0|    257.87|         62.6|          4.35|        Rework|              No|     Anita|
|    PR0073059|     2026-04-01|    PL01|     MC003|     OP0110|Evening|     MTR-200|        Motors|         1198|          1239|             11|               0|     282.6|        50.32|          3.91|        Rework|              No|     Gopal|
|    PR0103247|     2026-10-12|    PL05|     MC024|     OP0529|  Night|     CTL-230|   Controllers|         1195|          1239|             39|             165|    617.61|        69.15|          3.33|          Pass|              No|     Deepa|
|    PR0103306|     2026-06-09|    PL06|     MC026|     OP0015|  Night|     PMP-110|         Pumps|         1197|          1239|             30|              19|    390.78|        62.21|          2.96|          Pass|             Yes|     Farah|
|    PR0117602|     2026-02-13|    PL03|     MC012|     OP0368|Evening|     MTR-100|        Motors|         1197|          1239|             27|              38|    521.93|        69.64|          2.28|          Pass|              No|    Bharat|
|    PR0033781|     2026-04-18|    PL05|     MC022|     OP0254|Evening|     PMP-310|         Pumps|         1200|          1238|             36|              41|    617.76|        72.83|           4.8|          Pass|              No|    Charan|
|    PR0098449|     2026-08-11|    PL05|     MC022|     OP0049|Morning|     PMP-110|         Pumps|         1198|          1238|             58|              47|    600.77|        63.45|          3.29|          Pass|              No|     Irfan|
|    PR0074297|     2026-05-20|    PL04|     MC019|     OP0142|Morning|     MTR-200|        Motors|         1195|          1238|             23|               0|     331.2|        66.75|           4.1|          Pass|              No|     Deepa|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

In [54]:
df.orderBy(col("defective_units").desc()).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0051359|     2026-09-16|    PL02|     MC009|     OP0181|Morning|     CTL-230|   Controllers|         1192|          1230|            108|               8|    555.34|        71.97|          2.09|        Rework|              No|     Irfan|
|    PR0108009|     2026-06-07|    PL05|     MC023|     OP0417|Morning|     CTL-230|   Controllers|         1061|          1067|            106|               0|    491.74|         NULL|          4.93|        Rework|             Yes|     Farah|
|    PR0067365|     2026-05-13|    PL01|     MC001|     OP0461|Evening|     MTR-100|        Motors|         1189|          1186|            103|               0|    373.15|        64.44|          4.27|        Reject|             Yes|     Farah|
|    PR0070440|     2026-05-23|    PL04|     MC018|     OP0033|  Night|     VLV-120|        Valves|         1133|          1124|            102|               0|    238.46|        71.28|          2.79|        Reject|              No|     Deepa|
|    PR0082514|     2026-03-18|    PL04|     MC017|     OP0007|Morning|     PMP-310|         Pumps|         1181|          1109|            100|              19|    331.99|        56.53|          2.97|        Reject|              No|     Anita|
|    PR0106744|     2026-04-27|    PL01|     MC003|     OP0094|Evening|     CTL-130|   Controllers|         1084|          1103|            100|               0|    465.02|        68.15|          2.18|        Rework|              No|    Charan|
|    PR0013103|     2026-05-06|    PL02|     MC009|     OP0159|Morning|     MTR-100|        Motors|         1042|           990|             97|              30|    196.72|        57.62|          3.46|        Rework|              No|    Harini|
|    PR0045241|     2026-01-04|    PL03|     MC013|     OP0202|Morning|     VLV-320|        Valves|         1197|          1231|             96|              23|    456.16|         63.5|          1.55|        Rework|              No|    Harini|
|    PR0103867|     2026-06-07|    PL04|     MC017|     OP0033|Morning|     PMP-310|         Pumps|         1088|          1095|             95|              29|    411.22|        62.63|           0.4|        Rework|              No|     Irfan|
|    PR0043427|     2026-02-04|    PL04|     MC017|     OP0003|Morning|     VLV-120|        Valves|         1170|          1196|             95|              19|    218.83|        65.99|          NULL|        Rework|              No|     Deepa|
|    PR0068424|     2026-07-18|    PL06|     MC027|     OP0609|Evening|     VLV-320|        Valves|         1052|          1073|             93|              52|    406.85|         57.3|          4.71|        Reject|             Yes|    Harini|
|    PR0014350|     2026-09-27|    PL05|     MC023|     OP0458|Evening|     CTL-330|   Controllers|         1120|          1128|             91|               7|    250.83|        61.73|          4.66|        Rework|              No|     Farah|
|    PR0068990|     2026-02-02|    PL01|     MC004|     OP0210|Evening|     CTL-230|   Controllers|         1136|          1104|             91|              47|    232.35|        61.59|          3.57|        Reject|              No|     Farah|
|    PR0078536|     2026-05-11|    PL03|     MC012|     OP0486|  Night|     PMP-110|         Pumps|         1141|          1095|             91|              51|    301.78|        62.09|          3.48|        Rework|              No|     Farah|
|    PR0039878|     2026-07-28|    PL05|     MC022|     OP0464|Evening|     MTR-100|        Motors|         1052|           990|             90|              14|    341.79|        57.54|           3.7|        Reject|              No|    Charan|
|    PR0082255|     2026-09-01|    PL02|     MC007|     OP0528|  Night|     VLV-320|        Valves|         1174|          1123|             89|              20|    314.99|        71.07|          0.83|        Rework|              No|     Gopal|
|    PR0085319|     2026-09-23|    PL05|     MC024|     OP0399|Morning|     VLV-120|        Valves|          973|           970|             89|              52|    390.03|         59.4|          1.64|        Rework|             Yes|     Irfan|
|    PR0027472|     2026-10-22|    PL04|     MC016|     OP0340|Morning|     CTL-330|   Controllers|         1100|           960|             88|              40|    341.48|        51.33|          4.22|        Rework|              No|    Harini|
|    PR0116375|     2026-01-06|    PL03|     MC015|     OP0318|  Night|     MTR-200|        Motors|         1174|          1206|             88|              68|    405.22|        57.62|          4.43|        Rework|              No|     Farah|
|    PR0064147|     2026-07-28|    PL01|     MC004|     OP0105|Evening|     MTR-100|        Motors|         1162|          1159|             88|               0|    297.53|        58.15|           0.4|        Rework|              No|     Gopal|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

In [55]:
df.sort(col("plant_id").asc(), col("units_produced").desc()).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0073059|     2026-04-01|    PL01|     MC003|     OP0110|Evening|     MTR-200|        Motors|         1198|          1239|             11|               0|     282.6|        50.32|          3.91|        Rework|              No|     Gopal|
|    PR0002678|     2026-04-06|    PL01|     MC005|     OP0509|  Night|     CTL-130|   Controllers|         1194|          1238|             68|              30|    305.77|        69.09|          3.41|        Reject|              No|    Harini|
|    PR0005192|     2026-09-08|    PL01|     MC002|     OP0075|Morning|     MTR-300|        Motors|         1195|          1236|             12|              49|    349.97|         81.8|          2.95|          Pass|              No|     Gopal|
|    PR0044516|     2026-10-10|    PL01|     MC002|     OP0513|Morning|     MTR-200|        Motors|         1200|          1236|             25|              37|    233.63|        75.95|          1.82|          Pass|              No|     Gopal|
|    PR0056319|     2026-06-07|    PL01|     MC002|     OP0453|Evening|     CTL-130|   Controllers|         1193|          1236|              4|              24|    617.25|        46.98|          4.71|          Pass|             Yes|     Farah|
|    PR0006350|     2026-02-04|    PL01|     MC004|     OP0322|  Night|     PMP-110|         Pumps|         1193|          1234|             38|              27|    585.43|        59.48|          2.58|          Pass|             Yes|     Anita|
|    PR0046906|     2026-04-21|    PL01|     MC005|     OP0649|Evening|     CTL-230|   Controllers|         1199|          1233|             75|              42|    392.44|        69.03|          2.04|        Reject|             Yes|     Gopal|
|    PR0046582|     2026-07-18|    PL01|     MC002|     OP0040|  Night|     MTR-100|        Motors|         1190|          1230|              3|              34|    232.68|        51.69|          4.69|        Reject|              No|     Irfan|
|    PR0097172|     2026-01-29|    PL01|     MC002|     OP0257|  Night|     PMP-310|         Pumps|         1198|          1229|             55|              30|    444.46|        71.27|          4.99|        Rework|              No|     Deepa|
|    PR0024941|     2026-04-21|    PL01|     MC002|     OP0101|Evening|     VLV-120|        Valves|         1193|          1229|             25|             117|    310.61|        65.69|          2.64|        Reject|              No|    Harini|
|    PR0088933|     2026-03-04|    PL01|     MC003|     OP0492|Morning|     MTR-300|        Motors|         1190|          1229|             51|              34|    267.82|        78.75|          4.76|        Rework|              No|    Bharat|
|    PR0048075|     2026-03-05|    PL01|     MC005|     OP0171|Evening|     PMP-310|         Pumps|         1196|          1228|             14|              12|    569.62|        54.97|          4.02|          Pass|              No|    Harini|
|    PR0083644|     2026-07-13|    PL01|     MC005|     OP0043|Evening|     PMP-310|         Pumps|         1188|          1228|             16|              30|    533.46|        70.21|          4.53|          Pass|              No|    Bharat|
|    PR0002284|     2026-08-31|    PL01|     MC004|     OP0639|Evening|     PMP-110|         Pumps|         1192|          1227|             30|               0|    438.15|        66.08|          3.65|        Rework|              No|     Farah|
|    PR0109962|     2026-03-06|    PL01|     MC001|     OP0536|Evening|     MTR-300|        Motors|         1199|          1227|             16|              15|    280.96|        52.32|          2.04|          Pass|              No|     Gopal|
|    PR0012821|     2026-07-14|    PL01|     MC005|     OP0195|Morning|     CTL-130|   Controllers|         1192|          1226|              7|              58|     625.8|        57.83|          2.22|        Reject|              No|     Farah|
|    PR0119269|     2026-06-22|    PL01|     MC005|     OP0125|Evening|     MTR-200|        Motors|         1182|          1226|             21|              33|    268.92|        67.94|          2.68|        Reject|              No|     Farah|
|    PR0000300|     2026-05-07|    PL01|     MC003|     OP0478|Evening|     VLV-320|        Valves|         1181|          1226|             31|              35|    359.21|         69.8|          3.13|        Reject|              No|     Farah|
|    PR0083683|     2026-04-10|    PL01|     MC002|     OP0268|Evening|     MTR-200|        Motors|         1188|          1226|             16|              45|    455.05|        59.46|          3.55|          Pass|              No|     Anita|
|    PR0022084|     2026-01-26|    PL01|     MC004|     OP0396|Morning|     PMP-310|         Pumps|         1198|          1226|             38|              15|    617.55|        69.97|          3.97|        Reject|             Yes|     Deepa|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

In [56]:
df.sort(col("units_produced").desc()).show(20)

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0087560|     2026-06-29|    PL04|     MC018|     OP0587|  Night|     VLV-120|        Valves|         1199|          1245|             60|               0|    500.87|        58.11|          3.58|          Pass|             Yes|    Charan|
|    PR0008535|     2026-02-23|    PL04|     MC018|     OP0286|Morning|     MTR-200|        Motors|         1199|          1245|              0|              53|    257.72|        60.24|           2.6|          Pass|              No|     Farah|
|    PR0100473|     2026-10-18|    PL02|     MC009|     OP0559|  Night|     CTL-230|   Controllers|         1198|          1245|             53|              16|    375.27|         58.3|          2.82|        Reject|              No|     Irfan|
|    PR0098612|     2026-09-02|    PL05|     MC024|     OP0268|Morning|     PMP-210|         Pumps|         1199|          1245|             23|               0|    350.65|        56.41|          2.13|          Pass|              No|    Bharat|
|    PR0010732|     2026-09-26|    PL02|     MC007|     OP0496|Evening|     PMP-210|         Pumps|         1200|          1243|              0|               0|    599.61|        75.16|           1.8|          Pass|              No|     Gopal|
|    PR0082579|     2026-01-20|    PL03|     MC013|     OP0313|Morning|     MTR-100|        Motors|         1200|          1243|              1|              40|    517.17|        51.05|          3.65|        Rework|              No|    Charan|
|    PR0047939|     2026-09-28|    PL04|     MC020|     OP0174|Evening|     PMP-210|         Pumps|         1199|          1243|             42|              28|    502.25|        66.71|          2.97|          Pass|              No|     Anita|
|    PR0001765|     2026-09-15|    PL02|     MC006|     OP0088|  Night|     MTR-300|        Motors|         1195|          1242|              0|               0|    303.92|        58.93|          4.05|        Reject|             Yes|     Deepa|
|    PR0069661|     2026-01-28|    PL04|     MC020|     OP0499|Evening|     CTL-130|   Controllers|         1200|          1242|             13|              40|     392.3|         NULL|           2.7|          Pass|             Yes|     Irfan|
|    PR0064142|     2026-01-10|    PL06|     MC028|     OP0332|Morning|     PMP-310|         Pumps|         1195|          1241|             39|              41|    547.34|        77.31|          3.18|          Pass|              No|    Harini|
|    PR0116814|     2026-04-16|    PL05|     MC022|     OP0125|Evening|     CTL-130|   Controllers|         1200|          1240|             22|              50|    515.01|        68.24|          3.18|          Pass|              No|    Charan|
|    PR0030298|     2026-05-04|    PL03|     MC011|     OP0514|  Night|     CTL-130|   Controllers|         1195|          1239|             30|              74|    616.84|        60.83|          5.16|          Pass|              No|    Harini|
|    PR0093782|     2026-06-01|    PL04|     MC020|     OP0240|Evening|     VLV-320|        Valves|         1192|          1239|             10|               0|    257.87|         62.6|          4.35|        Rework|              No|     Anita|
|    PR0073059|     2026-04-01|    PL01|     MC003|     OP0110|Evening|     MTR-200|        Motors|         1198|          1239|             11|               0|     282.6|        50.32|          3.91|        Rework|              No|     Gopal|
|    PR0103247|     2026-10-12|    PL05|     MC024|     OP0529|  Night|     CTL-230|   Controllers|         1195|          1239|             39|             165|    617.61|        69.15|          3.33|          Pass|              No|     Deepa|
|    PR0103306|     2026-06-09|    PL06|     MC026|     OP0015|  Night|     PMP-110|         Pumps|         1197|          1239|             30|              19|    390.78|        62.21|          2.96|          Pass|             Yes|     Farah|
|    PR0117602|     2026-02-13|    PL03|     MC012|     OP0368|Evening|     MTR-100|        Motors|         1197|          1239|             27|              38|    521.93|        69.64|          2.28|          Pass|              No|    Bharat|
|    PR0033781|     2026-04-18|    PL05|     MC022|     OP0254|Evening|     PMP-310|         Pumps|         1200|          1238|             36|              41|    617.76|        72.83|           4.8|          Pass|              No|    Charan|
|    PR0098449|     2026-08-11|    PL05|     MC022|     OP0049|Morning|     PMP-110|         Pumps|         1198|          1238|             58|              47|    600.77|        63.45|          3.29|          Pass|              No|     Irfan|
|    PR0074297|     2026-05-20|    PL04|     MC019|     OP0142|Morning|     MTR-200|        Motors|         1195|          1238|             23|               0|     331.2|        66.75|           4.1|          Pass|              No|     Deepa|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

In [57]:
df.sort(col("downtime_minutes").desc()).show(10)

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0092818|     2026-02-16|    PL06|     MC027|     OP0016|Morning|     PMP-210|         Pumps|         1066|           907|              2|             281|    359.48|        54.03|           2.8|          Pass|              No|     Farah|
|    PR0045363|     2026-07-07|    PL02|     MC010|     OP0215|  Night|     CTL-330|   Controllers|          502|           463|              3|             278|    112.25|        72.69|          4.03|          Pass|              No|    Bharat|
|    PR0020842|     2026-04-28|    PL02|     MC008|     OP0003|  Night|     MTR-200|        Motors|         1004|           985|             24|             267|    326.53|        53.78|          3.82|        Reject|              No|    Harini|
|    PR0065023|     2026-02-11|    PL06|     MC029|     OP0249|Evening|     CTL-230|   Controllers|          708|           654|             23|             267|    220.98|         67.8|           4.8|          Pass|              No|     Deepa|
|    PR0068768|     2026-03-27|    PL03|     MC012|     OP0098|  Night|     MTR-200|        Motors|          958|           898|             15|             267|     172.3|        64.62|          4.59|          Pass|              No|     Farah|
|    PR0100950|     2026-01-16|    PL03|     MC012|     OP0076|Evening|     MTR-100|        Motors|          977|           900|             13|             263|     401.3|        66.18|          1.91|          Pass|              No|    Charan|
|    PR0041129|     2026-02-06|    PL01|     MC005|     OP0338|Morning|     PMP-110|         Pumps|          374|           361|              6|             263|    158.25|        71.94|          3.47|          Pass|              No|     Gopal|
|    PR0049997|     2026-08-30|    PL04|     MC019|     OP0337|  Night|     PMP-310|         Pumps|          584|           575|              7|             263|    292.82|        42.51|          5.13|          Pass|             Yes|     Farah|
|    PR0022495|     2026-06-18|    PL05|     MC022|     OP0619|Evening|     VLV-120|        Valves|         1172|          1141|             56|             262|     265.5|        53.16|          4.48|          Pass|              No|    Charan|
|    PR0112855|     2026-03-28|    PL02|     MC008|     OP0589|Morning|     MTR-100|        Motors|          319|           269|              2|             261|     92.92|         69.9|          2.57|          Pass|             Yes|    Harini|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 10 rows

In [58]:
df.select("machine_id", "vibration_mm_s") \
  .sort(col("vibration_mm_s").desc()) \
  .show()

+----------+--------------+
|machine_id|vibration_mm_s|
+----------+--------------+
|     MC012|          8.56|
|     MC030|          8.25|
|     MC027|          7.85|
|     MC010|           7.8|
|     MC018|          7.79|
|     MC024|          7.77|
|     MC015|          7.76|
|     MC027|          7.75|
|     MC015|          7.67|
|     MC016|          7.63|
|     MC007|          7.61|
|     MC010|          7.59|
|     MC027|          7.58|
|     MC017|          7.52|
|     MC021|           7.5|
|     MC021|           7.5|
|     MC004|          7.48|
|     MC027|          7.47|
|     MC025|          7.46|
|     MC019|          7.45|
+----------+--------------+
only showing top 20 rows

Aggregations:

1. Total units planned.
2. Total units produced.
3. Total defective units.
4. Average units produced.
5. Maximum production output.
6. Minimum production output.
7. Average downtime.
8. Total energy consumed.
9. Average temperature.
10. Average vibration.

In [59]:
from pyspark.sql.functions import sum, avg, min, max, count, col

In [60]:
df.select(sum("units_planned").alias("total_units_planned")).show()

+-------------------+
|total_units_planned|
+-------------------+
|           87094621|
+-------------------+

In [61]:
df.select(sum("units_produced").alias("total_units_produced")).show()

+--------------------+
|total_units_produced|
+--------------------+
|            80927888|
+--------------------+

In [62]:
df.select(sum("defective_units").alias("total_defective_units")).show()

+---------------------+
|total_defective_units|
+---------------------+
|              2030244|
+---------------------+

In [63]:
df.select(avg("units_produced").alias("avg_units_produced")).show()

+------------------+
|avg_units_produced|
+------------------+
| 674.3990666666666|
+------------------+

In [64]:
df.select(max("units_produced").alias("max_production_output")).show()

+---------------------+
|max_production_output|
+---------------------+
|                 1245|
+---------------------+

In [65]:
df.select(min("units_produced").alias("min_production_output")).show()

+---------------------+
|min_production_output|
+---------------------+
|                  205|
+---------------------+

In [66]:
df.select(avg("downtime_minutes").alias("avg_downtime")).show()

+-----------------+
|     avg_downtime|
+-----------------+
|33.93149474428351|
+-----------------+

In [67]:
df.select(sum("energy_kwh").alias("total_energy_consumed")).show()

+---------------------+
|total_energy_consumed|
+---------------------+
| 2.8368014080000117E7|
+---------------------+

In [68]:
df.select(avg("temperature_c").alias("avg_temperature")).show()

+------------------+
|   avg_temperature|
+------------------+
|63.021532392167266|
+------------------+

In [69]:
df.select(avg("vibration_mm_s").alias("avg_vibration")).show()

+-----------------+
|    avg_vibration|
+-----------------+
|3.398737691604917|
+-----------------+

groupBy():

Find:
1. Total production by plant.
2. Total production by product family.
3. Total defects by plant.
4. Average downtime by shift.
5. Average energy usage by product family.
6. Production count by quality status.
7. Production by plant and shift.
8. Defects by plant and product family.
9. Average temperature by machine.
10. Total output by supervisor.
Then sort each summary appropriately.

In [70]:
df.groupBy("plant_id").agg(sum("units_produced").alias("total_production")).sort(col("total_production").desc()).show()

+--------+----------------+
|plant_id|total_production|
+--------+----------------+
|    PL03|        13547769|
|    PL02|        13546452|
|    PL04|        13529935|
|    PL06|        13492337|
|    PL01|        13488232|
|    PL05|        13323163|
+--------+----------------+

In [71]:
df.groupBy("product_family").agg(sum("units_produced").alias("total_production")).sort(col("total_production").desc()).show()

+--------------+----------------+
|product_family|total_production|
+--------------+----------------+
|        Valves|        20433082|
|         Pumps|        20208739|
|   Controllers|        20168572|
|        Motors|        20117495|
+--------------+----------------+

In [72]:
df.groupBy("plant_id").agg(sum("defective_units").alias("total_defects")).sort(col("total_defects").desc()).show()

+--------+-------------+
|plant_id|total_defects|
+--------+-------------+
|    PL01|       339720|
|    PL02|       339647|
|    PL03|       339264|
|    PL06|       338993|
|    PL04|       338118|
|    PL05|       334502|
+--------+-------------+

In [73]:
df.groupBy("shift").agg(avg("downtime_minutes").alias("avg_downtime")).sort(col("avg_downtime").desc()).show()

+-------+------------------+
|  shift|      avg_downtime|
+-------+------------------+
|Evening|  34.2213017151833|
|  Night|33.953058820580935|
|Morning| 33.61973080530278|
+-------+------------------+

In [74]:
df.groupBy("product_family").agg(avg("energy_kwh").alias("avg_energy")).sort(col("avg_energy").desc()).show()

+--------------+------------------+
|product_family|        avg_energy|
+--------------+------------------+
|        Motors|237.21818224597516|
|         Pumps|236.89137927582252|
|        Valves|236.34508750495314|
|   Controllers|235.15370433333288|
+--------------+------------------+

In [75]:
df.groupBy("quality_status").count().sort(col("count").desc()).show()

+--------------+-----+
|quality_status|count|
+--------------+-----+
|          Pass|74328|
|        Rework|22928|
|        Reject|22744|
+--------------+-----+

In [76]:
df.groupBy("plant_id", "shift").agg(sum("units_produced").alias("total_production")).sort("plant_id", "shift").show()

+--------+-------+----------------+
|plant_id|  shift|total_production|
+--------+-------+----------------+
|    PL01|Evening|         4477769|
|    PL01|Morning|         4447851|
|    PL01|  Night|         4562612|
|    PL02|Evening|         4426917|
|    PL02|Morning|         4561068|
|    PL02|  Night|         4558467|
|    PL03|Evening|         4487211|
|    PL03|Morning|         4460950|
|    PL03|  Night|         4599608|
|    PL04|Evening|         4540617|
|    PL04|Morning|         4497099|
|    PL04|  Night|         4492219|
|    PL05|Evening|         4475101|
|    PL05|Morning|         4431446|
|    PL05|  Night|         4416616|
|    PL06|Evening|         4458798|
|    PL06|Morning|         4429107|
|    PL06|  Night|         4604432|
+--------+-------+----------------+

In [77]:
df.groupBy("plant_id", "product_family").agg(sum("defective_units").alias("total_defects")).sort(col("total_defects").desc()).show()

+--------+--------------+-------------+
|plant_id|product_family|total_defects|
+--------+--------------+-------------+
|    PL02|   Controllers|        87120|
|    PL01|         Pumps|        87103|
|    PL04|        Valves|        87084|
|    PL06|   Controllers|        86140|
|    PL06|        Valves|        85570|
|    PL03|        Valves|        85333|
|    PL03|        Motors|        84926|
|    PL01|        Valves|        84874|
|    PL03|         Pumps|        84803|
|    PL02|        Motors|        84560|
|    PL02|         Pumps|        84491|
|    PL05|        Motors|        84331|
|    PL03|   Controllers|        84202|
|    PL01|        Motors|        84174|
|    PL04|         Pumps|        83976|
|    PL04|        Motors|        83897|
|    PL06|         Pumps|        83884|
|    PL05|         Pumps|        83607|
|    PL05|   Controllers|        83589|
|    PL01|   Controllers|        83569|
+--------+--------------+-------------+
only showing top 20 rows

In [78]:
df.groupBy("machine_id").agg(avg("temperature_c").alias("avg_temp")).sort(col("avg_temp").desc()).show()

+----------+------------------+
|machine_id|          avg_temp|
+----------+------------------+
|     MC019|63.266223444138944|
|     MC020| 63.22489208633087|
|     MC029| 63.13119731057668|
|     MC009|  63.1252779855396|
|     MC014|63.114309957574186|
|     MC023|63.109051746112684|
|     MC027|63.099668282725126|
|     MC022| 63.09403431245128|
|     MC015| 63.09026488395557|
|     MC001|  63.0778733146782|
|     MC017| 63.07674442190667|
|     MC011|63.060230414746606|
|     MC007|   63.037661716587|
|     MC016| 63.03639870582378|
|     MC026| 63.02672521957329|
|     MC021| 63.01464069491981|
|     MC005|62.979236446933044|
|     MC028| 62.97779683034558|
|     MC030| 62.96733774497327|
|     MC024| 62.96457946271644|
+----------+------------------+
only showing top 20 rows

In [79]:
df.groupBy("supervisor").agg(sum("units_produced").alias("total_output")).sort(col("total_output").desc()).show()

+----------+------------+
|supervisor|total_output|
+----------+------------+
|     Farah|    10276986|
|    Harini|    10215803|
|     Deepa|    10130817|
|    Bharat|    10122430|
|     Anita|    10089966|
|    Charan|    10037116|
|     Gopal|    10031531|
|     Irfan|    10023239|
+----------+------------+

Joining DataFrames:

1. Inner join production with plant master.
2. Display plant name instead of only plant ID.
3. Join production with machine master.
4. Create one DataFrame containing production + plant + machine information.
5. Calculate total production by plant city.
6. Calculate average downtime by machine type.
7. Calculate defects by region.
8. Find production records without matching machine master records.
9. Perform a left join and inspect unmatched records.
10. Find total energy consumption by plant name.

In [80]:
plant_df = spark.read.csv("plant_master.csv", header=True, inferSchema=True)
machine_df = spark.read.csv("machine_master.csv", header=True, inferSchema=True)

In [81]:
prod_plant_df = df.join(plant_df, on="plant_id", how="inner")
prod_plant_df.show(5)

+--------+-------------+---------------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------+---------+------+-----------+-------------+
|plant_id|production_id|production_date|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|     plant_name|     city|region|year_opened|plant_manager|
+--------+-------------+---------------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------+---------+------+-----------+-------------+
|    PL03|    PR0000001|     2026-08-07|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|  Chennai Plant|  Chennai| South|       2015| A. Natarajan|
|    PL04|    PR0000002|     2026-08-03|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|    Noida Plant|    Noida| North|       2019|    M. Sharma|
|    PL01|    PR0000003|     2026-05-20|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|Hyderabad Plant|Hyderabad| South|       2016|     R. Menon|
|    PL03|    PR0000004|     2026-01-15|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|  Chennai Plant|  Chennai| South|       2015| A. Natarajan|
|    PL04|    PR0000005|     2026-09-21|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|    Noida Plant|    Noida| North|       2019|    M. Sharma|
+--------+-------------+---------------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------+---------+------+-----------+-------------+
only showing top 5 rows

In [82]:
prod_plant_df.select("production_id", "plant_name", "units_produced").show()

+-------------+---------------+--------------+
|production_id|     plant_name|units_produced|
+-------------+---------------+--------------+
|    PR0000001|  Chennai Plant|           993|
|    PR0000002|    Noida Plant|           836|
|    PR0000003|Hyderabad Plant|           380|
|    PR0000004|  Chennai Plant|           720|
|    PR0000005|    Noida Plant|           296|
|    PR0000006|Hyderabad Plant|           795|
|    PR0000007|     Pune Plant|           955|
|    PR0000008|     Pune Plant|           895|
|    PR0000009|  Chennai Plant|           289|
|    PR0000010|     Pune Plant|           527|
|    PR0000011|  Chennai Plant|           512|
|    PR0000012|  Kolkata Plant|           968|
|    PR0000013|  Kolkata Plant|           867|
|    PR0000014|  Chennai Plant|           456|
|    PR0000015|     Pune Plant|          1042|
|    PR0000016|    Noida Plant|           732|
|    PR0000017|  Chennai Plant|           963|
|    PR0000018|  Chennai Plant|           469|
|    PR0000019|Hyderabad Plant|           380|
|    PR0000020|  Chennai Plant|           573|
+-------------+---------------+--------------+
only showing top 20 rows

In [83]:
prod_machine_df = df.join(machine_df, on="machine_id", how="inner")
prod_machine_df.show(5)

+----------+-------------+---------------+--------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+--------+------------+-----------------+--------------+
|machine_id|production_id|production_date|plant_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|plant_id|machine_type|capacity_per_hour|installed_year|
+----------+-------------+---------------+--------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+--------+------------+-----------------+--------------+
|     MC011|    PR0000001|     2026-08-07|    PL03|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|    PL03|         CNC|              100|          2025|
|     MC019|    PR0000002|     2026-08-03|    PL04|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|    PL04|     Welding|               80|          2021|
|     MC002|    PR0000003|     2026-05-20|    PL01|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|    PL01|    Assembly|               80|          2024|
|     MC013|    PR0000004|     2026-01-15|    PL03|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|    PL03|     Casting|              180|          2020|
|     MC020|    PR0000005|     2026-09-21|    PL04|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|    PL04|     Testing|              120|          2018|
+----------+-------------+---------------+--------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+--------+------------+-----------------+--------------+
only showing top 5 rows

In [84]:
all_info_df = df.join(plant_df, on="plant_id", how="inner") \
              .join(machine_df, on="machine_id", how="inner")
all_info_df.show(5)

+----------+--------+-------------+---------------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------+---------+------+-----------+-------------+--------+------------+-----------------+--------------+
|machine_id|plant_id|production_id|production_date|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|     plant_name|     city|region|year_opened|plant_manager|plant_id|machine_type|capacity_per_hour|installed_year|
+----------+--------+-------------+---------------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------+---------+------+-----------+-------------+--------+------------+-----------------+--------------+
|     MC011|    PL03|    PR0000001|     2026-08-07|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|  Chennai Plant|  Chennai| South|       2015| A. Natarajan|    PL03|         CNC|              100|          2025|
|     MC019|    PL04|    PR0000002|     2026-08-03|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|    Noida Plant|    Noida| North|       2019|    M. Sharma|    PL04|     Welding|               80|          2021|
|     MC002|    PL01|    PR0000003|     2026-05-20|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|Hyderabad Plant|Hyderabad| South|       2016|     R. Menon|    PL01|    Assembly|               80|          2024|
|     MC013|    PL03|    PR0000004|     2026-01-15|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|  Chennai Plant|  Chennai| South|       2015| A. Natarajan|    PL03|     Casting|              180|          2020|
|     MC020|    PL04|    PR0000005|     2026-09-21|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|    Noida Plant|    Noida| North|       2019|    M. Sharma|    PL04|     Testing|              120|          2018|
+----------+--------+-------------+---------------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------+---------+------+-----------+-------------+--------+------------+-----------------+--------------+
only showing top 5 rows

In [85]:
all_info_df.groupBy("city").agg(sum("units_produced").alias("total_production")).show()

+---------+----------------+
|     city|total_production|
+---------+----------------+
|  Chennai|        13547769|
|Ahmedabad|        13323163|
|  Kolkata|        13492337|
|    Noida|        13529935|
|     Pune|        13546452|
|Hyderabad|        13488232|
+---------+----------------+

In [86]:
all_info_df.groupBy("machine_type").agg(avg("downtime_minutes").alias("avg_downtime")).show()

+------------+-----------------+
|machine_type|     avg_downtime|
+------------+-----------------+
|         CNC|33.64548129466162|
|     Testing|33.87585594724829|
|     Welding|34.00449382099613|
|    Assembly|33.96718284443325|
|     Casting| 34.1660783396419|
+------------+-----------------+

In [87]:
all_info_df.groupBy("region").agg(sum("defective_units").alias("total_defects")).show()

+------+-------------+
|region|total_defects|
+------+-------------+
| South|       678984|
|  East|       338993|
|  West|       674149|
| North|       338118|
+------+-------------+

In [88]:
unmatched_machines_df = df.join(machine_df, on="machine_id", how="left_anti")
unmatched_machines_df.show()

+----------+-------------+---------------+--------+-----------+-----+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|machine_id|production_id|production_date|plant_id|operator_id|shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+----------+-------------+---------------+--------+-----------+-----+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
+----------+-------------+---------------+--------+-----------+-----+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+

In [89]:
left_joined_df = df.join(machine_df, on="machine_id", how="left")
left_joined_df.filter(col("machine_type").isNull()).show()

+----------+-------------+---------------+--------+-----------+-----+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+--------+------------+-----------------+--------------+
|machine_id|production_id|production_date|plant_id|operator_id|shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|plant_id|machine_type|capacity_per_hour|installed_year|
+----------+-------------+---------------+--------+-----------+-----+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+--------+------------+-----------------+--------------+
+----------+-------------+---------------+--------+-----------+-----+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+--------+------------+-----------------+--------------+

In [90]:
all_info_df.groupBy("plant_name").agg(sum("energy_kwh").alias("total_energy")).show()

+---------------+-----------------+
|     plant_name|     total_energy|
+---------------+-----------------+
|    Noida Plant|4746238.580000002|
|  Kolkata Plant|4723180.160000009|
|  Chennai Plant|4742748.169999995|
|     Pune Plant|4757984.949999988|
|Hyderabad Plant|4725471.189999996|
|Ahmedabad Plant| 4672391.03000001|
+---------------+-----------------+

Updating Data

Remember that Spark transformations create new DataFrames rather than modifying rows in place.
Exercises:
1. Change Reject to Failed .
2. Change Rework to Requires Review .
3. Increase units planned by 5% for Motors.
4. Increase energy consumption by 3% for Night shifts.
5. Replace missing operator IDs with UNASSIGNED .
6. Replace supervisor Anita with Anita Rao .
7. Create a corrected temperature column.

In [91]:
from pyspark.sql.functions import col, when, coalesce, lit

In [92]:
df_update = df.withColumn(
    "quality_status",
    when(col("quality_status") == "Reject", "Failed")
    .otherwise(col("quality_status"))
)

df_update.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Failed|              No|     Farah|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Failed|              No|     Deepa|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Failed|              No|     Irfan|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Failed|              No|     Gopal|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

In [93]:
df2 = df_update.withColumn(
    "quality_status",
    when(col("quality_status") == "Rework", "Requires Review").otherwise(col("quality_status"))
)
df2.select("quality_status").distinct().show()

+---------------+
| quality_status|
+---------------+
|         Failed|
|Requires Review|
|           Pass|
+---------------+

In [94]:
df3 = df2.withColumn(
    "units_planned",
    when(col("product_family") == "Motors", col("units_planned") * 1.05).otherwise(col("units_planned"))
)
df3.select("product_family", "units_planned").show()

+--------------+------------------+
|product_family|     units_planned|
+--------------+------------------+
|        Motors|            1113.0|
|   Controllers|             809.0|
|        Motors|             464.1|
|         Pumps|             787.0|
|         Pumps|             344.0|
|        Motors|1005.9000000000001|
|        Valves|            1165.0|
|        Valves|             862.0|
|   Controllers|             313.0|
|   Controllers|             532.0|
|         Pumps|             577.0|
|   Controllers|             980.0|
|   Controllers|            1004.0|
|        Valves|             448.0|
|        Motors|            1140.3|
|   Controllers|             870.0|
|   Controllers|            1152.0|
|        Motors| 568.0500000000001|
|        Valves|             381.0|
|         Pumps|             646.0|
+--------------+------------------+
only showing top 20 rows

In [95]:
df4 = df3.withColumn(
    "energy_kwh",
    when(col("shift") == "Night", col("energy_kwh") * 1.03).otherwise(col("energy_kwh"))
)
df4.select("shift", "energy_kwh").show(5)

+-------+----------+
|  shift|energy_kwh|
+-------+----------+
|Evening|    388.11|
|Morning|    398.58|
|Evening|    183.34|
|Morning|    217.61|
|Morning|    115.47|
+-------+----------+
only showing top 5 rows

In [96]:
df5 = df4.withColumn(
    "operator_id",
    when(col("operator_id").isNull(), "UNASSIGNED").otherwise(col("operator_id"))
)
df5.select("operator_id").show(5)

+-----------+
|operator_id|
+-----------+
|     OP0275|
|     OP0489|
|     OP0189|
|     OP0076|
|     OP0501|
+-----------+
only showing top 5 rows

In [97]:
df6 = df5.withColumn(
    "supervisor",
    when(col("supervisor") == "Anita", "Anita Rao").otherwise(col("supervisor"))
)
df6.select("supervisor").distinct().show()

+----------+
|supervisor|
+----------+
|     Farah|
|    Harini|
|     Irfan|
|    Bharat|
|    Charan|
|     Gopal|
|     Deepa|
| Anita Rao|
+----------+

In [98]:
df7 = df6.withColumn(
    "corrected_temperature",
    when(col("temperature_c") < 0, lit(None)).otherwise(col("temperature_c"))
)
df7.select("temperature_c", "corrected_temperature").show()

+-------------+---------------------+
|temperature_c|corrected_temperature|
+-------------+---------------------+
|         61.4|                 61.4|
|        64.37|                64.37|
|        54.13|                54.13|
|        64.47|                64.47|
|        72.59|                72.59|
|        64.91|                64.91|
|        62.76|                62.76|
|         57.1|                 57.1|
|        66.55|                66.55|
|        60.96|                60.96|
|        52.81|                52.81|
|        69.79|                69.79|
|        50.88|                50.88|
|         67.2|                 67.2|
|        76.39|                76.39|
|        44.92|                44.92|
|        75.09|                75.09|
|        59.91|                59.91|
|        62.23|                62.23|
|        76.92|                76.92|
+-------------+---------------------+
only showing top 20 rows

Null Values and na Functions:


1. Count missing operator IDs.
2. Count missing temperature values.
3. Count missing vibration values.
4. Count missing downtime.
5. Use na.drop().
6. Drop only rows where temperature is missing.
7. Fill missing downtime with 0 .
8. Fill missing operator ID with UNKNOWN .
9. Fill missing temperature with the overall average temperature.
10. Compare record counts before and after cleansing.

In [99]:
df.select(count(when(col("operator_id").isNull(), 1)).alias("missing_operator_ids")).show()

+--------------------+
|missing_operator_ids|
+--------------------+
|                1524|
+--------------------+

In [100]:
df.select(count(when(col("temperature_c").isNull(), 1)).alias("missing_temperatures")).show()

+--------------------+
|missing_temperatures|
+--------------------+
|                2132|
+--------------------+

In [101]:
df.select(count(when(col("vibration_mm_s").isNull(), 1)).alias("missing_vibrations")).show()

+------------------+
|missing_vibrations|
+------------------+
|              1788|
+------------------+

In [102]:
df.select(count(when(col("downtime_minutes").isNull(), 1)).alias("missing_downtimes")).show()

+-----------------+
|missing_downtimes|
+-----------------+
|             1177|
+-----------------+

In [103]:
df_dropped = df.na.drop()
print("Records after using na.drop():", df_dropped.count())

Records after using na.drop(): 113531

In [104]:
df_temp_dropped = df.na.drop(subset=["temperature_c"])
print("Records after dropping missing temperature:", df_temp_dropped.count())

Records after dropping missing temperature: 117868

In [105]:
df_filled_downtime = df.na.fill({"downtime_minutes": 0})
df_filled_downtime.select("downtime_minutes").show()

+----------------+
|downtime_minutes|
+----------------+
|              34|
|               0|
|              15|
|              39|
|              49|
|              44|
|               5|
|              77|
|              16|
|              64|
|              32|
|              38|
|              66|
|               6|
|             172|
|              13|
|              91|
|              36|
|              25|
|              64|
+----------------+
only showing top 20 rows

In [106]:
df_filled_op_id = df.na.fill({"operator_id": "UNKNOWN"})
df_filled_op_id.select("operator_id").show()

+-----------+
|operator_id|
+-----------+
|     OP0275|
|     OP0489|
|     OP0189|
|     OP0076|
|     OP0501|
|     OP0501|
|     OP0645|
|     OP0106|
|     OP0386|
|     OP0593|
|     OP0141|
|     OP0047|
|     OP0172|
|     OP0446|
|     OP0238|
|     OP0013|
|     OP0533|
|     OP0162|
|     OP0526|
|     OP0563|
+-----------+
only showing top 20 rows

In [107]:
avg_temp = df.select(avg("temperature_c")).first()[0]
df_filled_temp = df.na.fill({"temperature_c": avg_temp})
df_filled_temp.select("temperature_c").show()

+-------------+
|temperature_c|
+-------------+
|         61.4|
|        64.37|
|        54.13|
|        64.47|
|        72.59|
|        64.91|
|        62.76|
|         57.1|
|        66.55|
|        60.96|
|        52.81|
|        69.79|
|        50.88|
|         67.2|
|        76.39|
|        44.92|
|        75.09|
|        59.91|
|        62.23|
|        76.92|
+-------------+
only showing top 20 rows

In [108]:
print("Original Record count: ", df.count())
print("Dropped DataFrame Record count: ", df_dropped.count())
print("Dropped Temperature DataFrame Record count: ", df_temp_dropped.count())

Original Record count:  120000
Dropped DataFrame Record count:  113531
Dropped Temperature DataFrame Record count:  117868

Built-in Functions:

1. Convert product family to uppercase.
2. Convert supervisor names to lowercase.
3. Trim operator IDs.
4. Find length of product codes.
5. Combine plant ID and machine ID.
6. Round temperature to one decimal.
7. Calculate absolute difference between planned and produced units.
8. Replace characters in production ID using regexp_replace .
9. Extract part of product code using substring .
10. Use coalesce() to return temperature or a default value.

In [109]:
from pyspark.sql.functions import (
    upper, lower, trim, length,
    concat, concat_ws, round, abs,
    coalesce, regexp_replace, substring, col, lit
)

In [110]:
df_upper = df.withColumn("product_family", upper(col("product_family")))

df_upper.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        MOTORS|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   CONTROLLERS|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        MOTORS|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         PUMPS|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         PUMPS|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        MOTORS|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        VALVES|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        VALVES|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   CONTROLLERS|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   CONTROLLERS|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         PUMPS|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   CONTROLLERS|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   CONTROLLERS|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        VALVES|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        MOTORS|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   CONTROLLERS|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   CONTROLLERS|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        MOTORS|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        VALVES|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         PUMPS|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

In [111]:
df_lower = df.withColumn("supervisor", lower(col("supervisor")))

df_lower.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    charan|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     farah|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     deepa|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     farah|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     deepa|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     gopal|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     gopal|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     irfan|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     anita|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     gopal|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    bharat|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     gopal|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     deepa|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     deepa|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     deepa|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     irfan|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     gopal|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     farah|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     deepa|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     irfan|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

In [112]:
df_trim = df.withColumn("operator_id", trim(col("operator_id")))

df_trim.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

In [113]:
df_length = df.withColumn("product_code_length", length(col("product_code")))

df_length.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+-------------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|product_code_length|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+-------------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|                  7|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|                  7|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|                  7|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|                  7|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|                  7|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|                  7|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|                  7|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|                  7|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|                  7|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|                  7|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|                  7|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|                  7|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|                  7|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|                  7|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|                  7|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|                  7|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|                  7|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|                  7|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|                  7|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|                  7|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+-------------------+
only showing top 20 rows

In [114]:
df_concat = df.withColumn("plant_machine", concat(col("plant_id"), lit("-"), col("machine_id")))

df_concat.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+-------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|plant_machine|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+-------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|   PL03-MC011|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|   PL04-MC019|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|   PL01-MC002|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|   PL03-MC013|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|   PL04-MC020|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|   PL01-MC002|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|   PL02-MC007|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|   PL02-MC009|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|   PL03-MC015|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|   PL02-MC006|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|   PL03-MC012|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|   PL06-MC030|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|   PL06-MC027|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|   PL03-MC013|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|   PL02-MC007|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|   PL04-MC020|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|   PL03-MC011|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|   PL03-MC012|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|   PL01-MC005|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|   PL03-MC014|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+-------------+
only showing top 20 rows

In [115]:
df_round = df.withColumn("temperature_rounded", round(col("temperature_c"), 1))

df_round.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+-------------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|temperature_rounded|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+-------------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|               61.4|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|               64.4|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|               54.1|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|               64.5|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|               72.6|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|               64.9|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|               62.8|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|               57.1|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|               66.6|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|               61.0|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|               52.8|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|               69.8|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|               50.9|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|               67.2|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|               76.4|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|               44.9|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|               75.1|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|               59.9|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|               62.2|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|               76.9|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+-------------------+
only showing top 20 rows

In [116]:
df_difference = df.withColumn("production_difference", abs(col("units_planned") - col("units_produced")))

df_difference.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|production_difference|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|                   67|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|                   27|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|                   62|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|                   67|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|                   48|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|                  163|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|                  210|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|                   33|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|                   24|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|                    5|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|                   65|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|                   12|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|                  137|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|                    8|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|                   44|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|                  138|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|                  189|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|                   72|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|                    1|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|                   73|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------------+
only showing top 20 rows

In [117]:
df_replace = df.withColumn("production_id_updated",
    regexp_replace(col("production_id"), "-", "_")
)

df_replace.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|production_id_updated|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|            PR0000001|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|            PR0000002|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|            PR0000003|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|            PR0000004|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|            PR0000005|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|            PR0000006|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|            PR0000007|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|            PR0000008|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|            PR0000009|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|            PR0000010|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|            PR0000011|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|            PR0000012|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|            PR0000013|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|            PR0000014|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|            PR0000015|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|            PR0000016|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|            PR0000017|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|            PR0000018|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|            PR0000019|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|            PR0000020|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------------+
only showing top 20 rows

In [118]:
df_substring = df.withColumn("product_code_part", substring(col("product_code"), 1, 6))

df_substring.select("product_code", "product_code_part").show()

+------------+-----------------+
|product_code|product_code_part|
+------------+-----------------+
|     MTR-100|           MTR-10|
|     CTL-330|           CTL-33|
|     MTR-300|           MTR-30|
|     PMP-210|           PMP-21|
|     PMP-110|           PMP-11|
|     MTR-300|           MTR-30|
|     VLV-120|           VLV-12|
|     VLV-320|           VLV-32|
|     CTL-130|           CTL-13|
|     CTL-230|           CTL-23|
|     PMP-210|           PMP-21|
|     CTL-330|           CTL-33|
|     CTL-330|           CTL-33|
|     VLV-220|           VLV-22|
|     MTR-300|           MTR-30|
|     CTL-330|           CTL-33|
|     CTL-330|           CTL-33|
|     MTR-100|           MTR-10|
|     VLV-320|           VLV-32|
|     PMP-310|           PMP-31|
+------------+-----------------+
only showing top 20 rows

In [119]:
df_coalesce = df.withColumn("temperature_filled", coalesce(col("temperature_c"), lit(38.0)))

df_coalesce.select("temperature_c", "temperature_filled").show()

+-------------+------------------+
|temperature_c|temperature_filled|
+-------------+------------------+
|         61.4|              61.4|
|        64.37|             64.37|
|        54.13|             54.13|
|        64.47|             64.47|
|        72.59|             72.59|
|        64.91|             64.91|
|        62.76|             62.76|
|         57.1|              57.1|
|        66.55|             66.55|
|        60.96|             60.96|
|        52.81|             52.81|
|        69.79|             69.79|
|        50.88|             50.88|
|         67.2|              67.2|
|        76.39|             76.39|
|        44.92|             44.92|
|        75.09|             75.09|
|        59.91|             59.91|
|        62.23|             62.23|
|        76.92|             76.92|
+-------------+------------------+
only showing top 20 rows

when() / otherwise():

Create:

1. Efficiency Category

        >= 100% → Above Target
        >= 95% → On Target
        >= 85% → Below Target
        otherwise → Critical

2. Defect Category

        0 → Perfect
        1–10 → Normal
        11–25 → Attention
        above 25 → High Defect

3. Machine Condition

Use temperature and vibration:

        High temperature OR high vibration → Inspect
        otherwise → Normal

Then count records in each resulting category.

In [120]:
df_efficiency_category = df.withColumn("production_efficiency", (col("units_produced") / col("units_planned")) * 100)

df_efficiency_category = df_efficiency_category.withColumn(
    "efficiency_category",
    when(
        col("production_efficiency") >= 100,
        "Above Target"
    ).when(
        col("production_efficiency") >= 95,
        "On Target"
    ).when(
        col("production_efficiency") >= 85,
        "Below Target"
    ).otherwise("Critical")
)

df_efficiency_category.select("production_id", "production_efficiency", "efficiency_category").show()

+-------------+---------------------+-------------------+
|production_id|production_efficiency|efficiency_category|
+-------------+---------------------+-------------------+
|    PR0000001|    93.67924528301886|       Below Target|
|    PR0000002|   103.33745364647713|       Above Target|
|    PR0000003|    85.97285067873304|       Below Target|
|    PR0000004|     91.4866581956798|       Below Target|
|    PR0000005|    86.04651162790698|       Below Target|
|    PR0000006|    82.98538622129436|           Critical|
|    PR0000007|    81.97424892703863|           Critical|
|    PR0000008|   103.82830626450117|       Above Target|
|    PR0000009|    92.33226837060703|       Below Target|
|    PR0000010|    99.06015037593986|          On Target|
|    PR0000011|    88.73483535528595|       Below Target|
|    PR0000012|    98.77551020408163|          On Target|
|    PR0000013|    86.35458167330677|       Below Target|
|    PR0000014|   101.78571428571428|       Above Target|
|    PR0000015|    95.94843462246777|          On Target|
|    PR0000016|    84.13793103448276|           Critical|
|    PR0000017|             83.59375|           Critical|
|    PR0000018|    86.69131238447319|       Below Target|
|    PR0000019|    99.73753280839895|          On Target|
|    PR0000020|    88.69969040247679|       Below Target|
+-------------+---------------------+-------------------+
only showing top 20 rows

In [121]:
df_defect_category = df.withColumn(
    "defect_category",
    when(
        col("defective_units") == 0,
        "Perfect"
    ).when(
        col("defective_units") <= 10,
        "Normal"
    ).when(
        col("defective_units") <= 25,
        "Attention"
    ).otherwise("High Defect")
)

df_defect_category.select("production_id", "defective_units", "defect_category").show()

+-------------+---------------+---------------+
|production_id|defective_units|defect_category|
+-------------+---------------+---------------+
|    PR0000001|             30|    High Defect|
|    PR0000002|              0|        Perfect|
|    PR0000003|             17|      Attention|
|    PR0000004|              7|         Normal|
|    PR0000005|              7|         Normal|
|    PR0000006|             50|    High Defect|
|    PR0000007|             10|         Normal|
|    PR0000008|             51|    High Defect|
|    PR0000009|              8|         Normal|
|    PR0000010|             26|    High Defect|
|    PR0000011|             14|      Attention|
|    PR0000012|             23|      Attention|
|    PR0000013|             27|    High Defect|
|    PR0000014|              6|         Normal|
|    PR0000015|              4|         Normal|
|    PR0000016|              0|        Perfect|
|    PR0000017|             28|    High Defect|
|    PR0000018|             18|      Attention|
|    PR0000019|             16|      Attention|
|    PR0000020|             13|      Attention|
+-------------+---------------+---------------+
only showing top 20 rows

In [122]:
df_machine_category = df.withColumn(
    "machine_condition",
    when(
        (col("temperature_c") > 80) | (col("vibration_mm_s") > 0.5), "Inspect"
    ).otherwise("Normal")
)

df_machine_category.select("production_id", "temperature_c", "vibration_mm_s", "machine_condition").show()

+-------------+-------------+--------------+-----------------+
|production_id|temperature_c|vibration_mm_s|machine_condition|
+-------------+-------------+--------------+-----------------+
|    PR0000001|         61.4|          3.88|          Inspect|
|    PR0000002|        64.37|          2.28|          Inspect|
|    PR0000003|        54.13|          4.66|          Inspect|
|    PR0000004|        64.47|          NULL|           Normal|
|    PR0000005|        72.59|          3.21|          Inspect|
|    PR0000006|        64.91|          2.77|          Inspect|
|    PR0000007|        62.76|          2.89|          Inspect|
|    PR0000008|         57.1|          1.34|          Inspect|
|    PR0000009|        66.55|          3.07|          Inspect|
|    PR0000010|        60.96|          3.48|          Inspect|
|    PR0000011|        52.81|          3.46|          Inspect|
|    PR0000012|        69.79|          3.43|          Inspect|
|    PR0000013|        50.88|           5.7|          Inspect|
|    PR0000014|         67.2|          3.12|          Inspect|
|    PR0000015|        76.39|          2.81|          Inspect|
|    PR0000016|        44.92|          4.81|          Inspect|
|    PR0000017|        75.09|           4.0|          Inspect|
|    PR0000018|        59.91|          3.87|          Inspect|
|    PR0000019|        62.23|          4.29|          Inspect|
|    PR0000020|        76.92|          2.35|          Inspect|
+-------------+-------------+--------------+-----------------+
only showing top 20 rows

In [123]:
print("Efficiency Categories:")
df_efficiency_category.groupBy("efficiency_category").count().show()

print("Defect Categories:")
df_defect_category.groupBy("defect_category").count().show()

print("Machine Condition Categories:")
df_machine_category.groupBy("machine_condition").count().show()

Efficiency Categories:
+-------------------+-----+
|efficiency_category|count|
+-------------------+-----+
|       Above Target|21735|
|          On Target|26825|
|       Below Target|54619|
|           Critical|16821|
+-------------------+-----+

Defect Categories:
+---------------+-----+
|defect_category|count|
+---------------+-----+
|      Attention|45745|
|        Perfect|11491|
|    High Defect|28058|
|         Normal|34706|
+---------------+-----+

Machine Condition Categories:
+-----------------+------+
|machine_condition| count|
+-----------------+------+
|          Inspect|117526|
|           Normal|  2474|
+-----------------+------+

Complex JSON:

1. Display schema.
2. Display machine ID and machine type.
3. Extract specifications.rated_power_kw .
4. Extract maximum temperature.
5. Extract vibration limit.
6. Display maintenance frequency.
7. Work with the sensors array.
8. Explode the sensors array.
9. Display one row per machine/sensor combination.
10. Find machines having an active temperature sensor.
11. Join machine configuration JSON with production data.

In [124]:
machine_json = spark.read.option("multiline", "true").json("machine_configurations.json")

In [125]:
machine_json.printSchema()

root
 |-- capacity_per_hour: long (nullable = true)
 |-- installed_year: long (nullable = true)
 |-- machine_id: string (nullable = true)
 |-- machine_type: string (nullable = true)
 |-- maintenance: struct (nullable = true)
 |    |-- frequency_days: long (nullable = true)
 |    |-- last_service: string (nullable = true)
 |-- plant_id: string (nullable = true)
 |-- sensors: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- active: boolean (nullable = true)
 |    |    |-- sensor: string (nullable = true)
 |    |    |-- unit: string (nullable = true)
 |-- specifications: struct (nullable = true)
 |    |-- max_temperature_c: long (nullable = true)
 |    |-- rated_power_kw: long (nullable = true)
 |    |-- vibration_limit_mm_s: double (nullable = true)

In [126]:
machine_json.select("machine_id", "machine_type").show(5)

+----------+------------+
|machine_id|machine_type|
+----------+------------+
|     MC001|         CNC|
|     MC002|    Assembly|
|     MC003|     Casting|
|     MC004|     Welding|
|     MC005|     Testing|
+----------+------------+
only showing top 5 rows

In [127]:
machine_json.select("machine_id", col("specifications.rated_power_kw")).show(5)

+----------+--------------+
|machine_id|rated_power_kw|
+----------+--------------+
|     MC001|            22|
|     MC002|            22|
|     MC003|            55|
|     MC004|            22|
|     MC005|            30|
+----------+--------------+
only showing top 5 rows

In [128]:
machine_json.select("machine_id", col("specifications.max_temperature_c")).show(5)

+----------+-----------------+
|machine_id|max_temperature_c|
+----------+-----------------+
|     MC001|               85|
|     MC002|               85|
|     MC003|               90|
|     MC004|               85|
|     MC005|               85|
+----------+-----------------+
only showing top 5 rows

In [129]:
machine_json.select("machine_id", col("specifications.vibration_limit_mm_s")).show(5)

+----------+--------------------+
|machine_id|vibration_limit_mm_s|
+----------+--------------------+
|     MC001|                 5.0|
|     MC002|                 5.5|
|     MC003|                 4.5|
|     MC004|                 4.5|
|     MC005|                 4.5|
+----------+--------------------+
only showing top 5 rows

In [130]:
machine_json.select("machine_id", "maintenance.frequency_days").show(5)

+----------+--------------+
|machine_id|frequency_days|
+----------+--------------+
|     MC001|            60|
|     MC002|            60|
|     MC003|            45|
|     MC004|            60|
|     MC005|            30|
+----------+--------------+
only showing top 5 rows

In [131]:
machine_json.select("machine_id", "sensors").show(5, truncate=False)

+----------+----------------------------------------------------------------------+
|machine_id|sensors                                                               |
+----------+----------------------------------------------------------------------+
|MC001     |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|
|MC002     |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|
|MC003     |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|
|MC004     |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|
|MC005     |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|
+----------+----------------------------------------------------------------------+
only showing top 5 rows

In [132]:
from pyspark.sql.functions import explode

df_sensors = machine_json.withColumn("sensor", explode(col("sensors")))
df_sensors.select("machine_id", "sensor").show(5, truncate=False)

+----------+-----------------------+
|machine_id|sensor                 |
+----------+-----------------------+
|MC001     |{true, temperature, C} |
|MC001     |{true, vibration, mm/s}|
|MC001     |{true, energy, kWh}    |
|MC002     |{true, temperature, C} |
|MC002     |{true, vibration, mm/s}|
+----------+-----------------------+
only showing top 5 rows

In [133]:
df_sensors.select("machine_id", "machine_type", "sensor.*").show(10)

+----------+------------+------+-----------+----+
|machine_id|machine_type|active|     sensor|unit|
+----------+------------+------+-----------+----+
|     MC001|         CNC|  true|temperature|   C|
|     MC001|         CNC|  true|  vibration|mm/s|
|     MC001|         CNC|  true|     energy| kWh|
|     MC002|    Assembly|  true|temperature|   C|
|     MC002|    Assembly|  true|  vibration|mm/s|
|     MC002|    Assembly|  true|     energy| kWh|
|     MC003|     Casting|  true|temperature|   C|
|     MC003|     Casting|  true|  vibration|mm/s|
|     MC003|     Casting|  true|     energy| kWh|
|     MC004|     Welding|  true|temperature|   C|
+----------+------------+------+-----------+----+
only showing top 10 rows

In [134]:
df_active_sensors = df_sensors.filter(
    (lower(col("sensor.sensor")).contains("temp")) & (col("sensor.active") == True)
).select("machine_id").distinct()

df_active_sensors.show()

+----------+
|machine_id|
+----------+
|     MC003|
|     MC018|
|     MC017|
|     MC009|
|     MC014|
|     MC007|
|     MC002|
|     MC024|
|     MC016|
|     MC026|
|     MC005|
|     MC010|
|     MC012|
|     MC023|
|     MC021|
|     MC020|
|     MC011|
|     MC013|
|     MC025|
|     MC028|
+----------+
only showing top 20 rows

In [135]:
df_machine_production = df.join(
    machine_json.drop("plant_id"),
    on="machine_id",
    how="inner"
)
df_machine_production.show(5)

+----------+-------------+---------------+--------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+-----------------+--------------+------------+----------------+--------------------+--------------+
|machine_id|production_id|production_date|plant_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|capacity_per_hour|installed_year|machine_type|     maintenance|             sensors|specifications|
+----------+-------------+---------------+--------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+-----------------+--------------+------------+----------------+--------------------+--------------+
|     MC011|    PR0000001|     2026-08-07|    PL03|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|              100|          2025|         CNC|{30, 2026-04-04}|[{true, temperatu...| {90, 30, 6.0}|
|     MC019|    PR0000002|     2026-08-03|    PL04|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|               80|          2021|     Welding|{30, 2026-07-27}|[{true, temperatu...| {75, 30, 5.0}|
|     MC002|    PR0000003|     2026-05-20|    PL01|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|               80|          2024|    Assembly|{60, 2026-05-19}|[{true, temperatu...| {85, 22, 5.5}|
|     MC013|    PR0000004|     2026-01-15|    PL03|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|              180|          2020|     Casting|{60, 2026-08-03}|[{true, temperatu...| {90, 30, 5.0}|
|     MC020|    PR0000005|     2026-09-21|    PL04|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|              120|          2018|     Testing|{45, 2026-09-17}|[{true, temperatu...| {80, 15, 5.0}|
+----------+-------------+---------------+--------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+-----------------+--------------+------------+----------------+--------------------+--------------+
only showing top 5 rows

Union and Union ALL:

1. Count records in the main DataFrame.
2. Count records in the extra DataFrame.
3. Combine using union() .
4. Combine using unionAll() .
5. Compare resulting counts.
6. Identify duplicate production_id values.
7. Remove duplicates after combining.
8. Compare unioned count before and after dropDuplicates() .
9. Try unionByName() .
10. Rearrange columns in one DataFrame and use unionByName() appropriately.

In [136]:
extra_df = spark.read.csv(
    "manufacturing_production_extra_12k.csv",
    header=True,
    inferSchema=True
)

extra_df.show(5)

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0120001|     2026-06-01|    PL05|     MC024|     OP0191|Evening|     PMP-210|         Pumps|          293|           292|             10|              44|    120.42|        70.59|          2.21|          Pass|             Yes|     Anita|
|    PR0120002|     2026-09-22|    PL01|     MC001|     OP0461|  Night|     MTR-100|        Motors|         1009|           897|             25|              59|    317.23|        81.74|          3.03|          Pass|              No|     Anita|
|    PR0120003|     2026-05-24|    PL03|     MC012|     OP0451|Evening|     MTR-100|        Motors|          960|           983|             34|               0|    350.82|        67.29|          2.01|          Pass|              No|     Deepa|
|    PR0120004|     2026-09-12|    PL04|     MC016|     OP0237|  Night|     CTL-130|   Controllers|          310|           320|             15|              14|    142.34|         59.7|          3.48|          Pass|              No|     Anita|
|    PR0120005|     2026-02-04|    PL04|     MC018|     OP0072|Morning|     VLV-220|        Valves|          957|           979|             22|              14|     296.7|        62.52|          2.33|          Pass|              No|    Harini|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 5 rows

In [137]:
print("Main DataFrame count:", df.count())
print("Extra DataFrame count:", extra_df.count())

Main DataFrame count: 120000
Extra DataFrame count: 12500

In [138]:
df_union = df.union(extra_df)

print("Union count:", df_union.count())

df_union.show(5)

Union count: 132500
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 5 rows

In [139]:
df_union_all = df.unionAll(extra_df)

print("Union ALL count:", df_union_all.count())

df_union_all.show(5)

Union ALL count: 132500
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 5 rows

In [140]:
print(f"Main records: {df.count()}")
print(f"Extra records: {extra_df.count()}")
print(f"Expected sum: {df.count() + extra_df.count()}")
print(f"union count: {df_union.count()}")
print(f"unionAll count: {df_union_all.count()}")

Main records: 120000
Extra records: 12500
Expected sum: 132500
union count: 132500
unionAll count: 132500

In [141]:
df_duplicates = df_union.groupBy("production_id").count().filter(col("count") > 1)

df_duplicates.show()

+-------------+-----+
|production_id|count|
+-------------+-----+
|    PR0000413|    2|
|    PR0000135|    2|
|    PR0000236|    2|
|    PR0000339|    2|
|    PR0000059|    2|
|    PR0000463|    2|
|    PR0000136|    2|
|    PR0000263|    2|
|    PR0000393|    2|
|    PR0000445|    2|
|    PR0000124|    2|
|    PR0000299|    2|
|    PR0000341|    2|
|    PR0000008|    2|
|    PR0000172|    2|
|    PR0000359|    2|
|    PR0000389|    2|
|    PR0000026|    2|
|    PR0000274|    2|
|    PR0000161|    2|
+-------------+-----+
only showing top 20 rows

In [142]:
df_no_duplicates = df_union.dropDuplicates(["production_id"])

print("Before removing duplicates:", df_union.count())
print("After removing duplicate rows:", df_no_duplicates.count())

Before removing duplicates: 132500
After removing duplicate rows: 132000

In [143]:
df_union_name = df.unionByName(extra_df)

df_union_name.show(5)

print("Union by name count:", df_union_name.count())

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 5 rows
Union by name count: 132500

In [144]:
reversed_cols = extra_df.columns[::-1]
df_extra_reordered = extra_df.select(reversed_cols)

df_reordered_union = df.unionByName(df_extra_reordered)
print("Count after unionByName with reordered columns:", df_reordered_union.count())

Count after unionByName with reordered columns: 132500

Window Functions:

1. Rank production records within each plant by units produced.
2. Use row_number() .
3. Use rank() .
4. Use dense_rank() .
5. Find top 5 production runs per plant.
6. Find top 3 machines by output within each plant.
7. Calculate total plant production without collapsing rows.
8. Calculate average machine output using a window.
9. Calculate cumulative production by machine ordered by date.
10. Display previous production output using lag() .
11. Display next production output using lead() .
12. Calculate change from the previous production run.
13. Rank product families by total output.

In [145]:
from pyspark.sql.window import Window
from pyspark.sql.functions import (row_number,rank,dense_rank,sum,avg,lag,lead,col)

In [146]:
window_plant = Window.partitionBy("plant_id").orderBy(col("units_produced").desc())

df_rank = df.withColumn("production_rank",rank().over(window_plant))

df_rank.select("plant_id","production_id","units_produced","production_rank").show()

+--------+-------------+--------------+---------------+
|plant_id|production_id|units_produced|production_rank|
+--------+-------------+--------------+---------------+
|    PL01|    PR0073059|          1239|              1|
|    PL01|    PR0002678|          1238|              2|
|    PL01|    PR0005192|          1236|              3|
|    PL01|    PR0044516|          1236|              3|
|    PL01|    PR0056319|          1236|              3|
|    PL01|    PR0006350|          1234|              6|
|    PL01|    PR0046906|          1233|              7|
|    PL01|    PR0046582|          1230|              8|
|    PL01|    PR0024941|          1229|              9|
|    PL01|    PR0088933|          1229|              9|
|    PL01|    PR0097172|          1229|              9|
|    PL01|    PR0048075|          1228|             12|
|    PL01|    PR0083644|          1228|             12|
|    PL01|    PR0002284|          1227|             14|
|    PL01|    PR0109962|          1227|             14|
|    PL01|    PR0000300|          1226|             16|
|    PL01|    PR0012821|          1226|             16|
|    PL01|    PR0022084|          1226|             16|
|    PL01|    PR0083683|          1226|             16|
|    PL01|    PR0119269|          1226|             16|
+--------+-------------+--------------+---------------+
only showing top 20 rows

In [147]:
df_row_number = df.withColumn("row_number", row_number().over(window_plant))

df_row_number.select("plant_id","production_id","units_produced","row_number").show()

+--------+-------------+--------------+----------+
|plant_id|production_id|units_produced|row_number|
+--------+-------------+--------------+----------+
|    PL01|    PR0073059|          1239|         1|
|    PL01|    PR0002678|          1238|         2|
|    PL01|    PR0005192|          1236|         3|
|    PL01|    PR0044516|          1236|         4|
|    PL01|    PR0056319|          1236|         5|
|    PL01|    PR0006350|          1234|         6|
|    PL01|    PR0046906|          1233|         7|
|    PL01|    PR0046582|          1230|         8|
|    PL01|    PR0024941|          1229|         9|
|    PL01|    PR0088933|          1229|        10|
|    PL01|    PR0097172|          1229|        11|
|    PL01|    PR0048075|          1228|        12|
|    PL01|    PR0083644|          1228|        13|
|    PL01|    PR0002284|          1227|        14|
|    PL01|    PR0109962|          1227|        15|
|    PL01|    PR0000300|          1226|        16|
|    PL01|    PR0012821|          1226|        17|
|    PL01|    PR0022084|          1226|        18|
|    PL01|    PR0083683|          1226|        19|
|    PL01|    PR0119269|          1226|        20|
+--------+-------------+--------------+----------+
only showing top 20 rows

In [148]:
df_rank = df.withColumn("rank",rank().over(window_plant))

df_rank.select("plant_id","production_id","units_produced","rank").show()

+--------+-------------+--------------+----+
|plant_id|production_id|units_produced|rank|
+--------+-------------+--------------+----+
|    PL01|    PR0073059|          1239|   1|
|    PL01|    PR0002678|          1238|   2|
|    PL01|    PR0005192|          1236|   3|
|    PL01|    PR0044516|          1236|   3|
|    PL01|    PR0056319|          1236|   3|
|    PL01|    PR0006350|          1234|   6|
|    PL01|    PR0046906|          1233|   7|
|    PL01|    PR0046582|          1230|   8|
|    PL01|    PR0024941|          1229|   9|
|    PL01|    PR0088933|          1229|   9|
|    PL01|    PR0097172|          1229|   9|
|    PL01|    PR0048075|          1228|  12|
|    PL01|    PR0083644|          1228|  12|
|    PL01|    PR0002284|          1227|  14|
|    PL01|    PR0109962|          1227|  14|
|    PL01|    PR0000300|          1226|  16|
|    PL01|    PR0012821|          1226|  16|
|    PL01|    PR0022084|          1226|  16|
|    PL01|    PR0083683|          1226|  16|
|    PL01|    PR0119269|          1226|  16|
+--------+-------------+--------------+----+
only showing top 20 rows

In [149]:
df_dense_rank = df.withColumn("dense_rank",dense_rank().over(window_plant))

df_dense_rank.select("plant_id","production_id","units_produced","dense_rank").show()

+--------+-------------+--------------+----------+
|plant_id|production_id|units_produced|dense_rank|
+--------+-------------+--------------+----------+
|    PL01|    PR0073059|          1239|         1|
|    PL01|    PR0002678|          1238|         2|
|    PL01|    PR0005192|          1236|         3|
|    PL01|    PR0044516|          1236|         3|
|    PL01|    PR0056319|          1236|         3|
|    PL01|    PR0006350|          1234|         4|
|    PL01|    PR0046906|          1233|         5|
|    PL01|    PR0046582|          1230|         6|
|    PL01|    PR0024941|          1229|         7|
|    PL01|    PR0088933|          1229|         7|
|    PL01|    PR0097172|          1229|         7|
|    PL01|    PR0048075|          1228|         8|
|    PL01|    PR0083644|          1228|         8|
|    PL01|    PR0002284|          1227|         9|
|    PL01|    PR0109962|          1227|         9|
|    PL01|    PR0000300|          1226|        10|
|    PL01|    PR0012821|          1226|        10|
|    PL01|    PR0022084|          1226|        10|
|    PL01|    PR0083683|          1226|        10|
|    PL01|    PR0119269|          1226|        10|
+--------+-------------+--------------+----------+
only showing top 20 rows

In [150]:
df_top5 = df.withColumn("row_number", row_number().over(window_plant)).filter(col("row_number") <= 5)

df_top5.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|row_number|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----------+
|    PR0073059|     2026-04-01|    PL01|     MC003|     OP0110|Evening|     MTR-200|        Motors|         1198|          1239|             11|               0|     282.6|        50.32|          3.91|        Rework|              No|     Gopal|         1|
|    PR0002678|     2026-04-06|    PL01|     MC005|     OP0509|  Night|     CTL-130|   Controllers|         1194|          1238|             68|              30|    305.77|        69.09|          3.41|        Reject|              No|    Harini|         2|
|    PR0005192|     2026-09-08|    PL01|     MC002|     OP0075|Morning|     MTR-300|        Motors|         1195|          1236|             12|              49|    349.97|         81.8|          2.95|          Pass|              No|     Gopal|         3|
|    PR0044516|     2026-10-10|    PL01|     MC002|     OP0513|Morning|     MTR-200|        Motors|         1200|          1236|             25|              37|    233.63|        75.95|          1.82|          Pass|              No|     Gopal|         4|
|    PR0056319|     2026-06-07|    PL01|     MC002|     OP0453|Evening|     CTL-130|   Controllers|         1193|          1236|              4|              24|    617.25|        46.98|          4.71|          Pass|             Yes|     Farah|         5|
|    PR0100473|     2026-10-18|    PL02|     MC009|     OP0559|  Night|     CTL-230|   Controllers|         1198|          1245|             53|              16|    375.27|         58.3|          2.82|        Reject|              No|     Irfan|         1|
|    PR0010732|     2026-09-26|    PL02|     MC007|     OP0496|Evening|     PMP-210|         Pumps|         1200|          1243|              0|               0|    599.61|        75.16|           1.8|          Pass|              No|     Gopal|         2|
|    PR0001765|     2026-09-15|    PL02|     MC006|     OP0088|  Night|     MTR-300|        Motors|         1195|          1242|              0|               0|    303.92|        58.93|          4.05|        Reject|             Yes|     Deepa|         3|
|    PR0027036|     2026-08-03|    PL02|     MC010|     OP0285|Morning|     MTR-200|        Motors|         1191|          1238|             12|              64|    583.51|         NULL|          2.95|          Pass|              No|    Charan|         4|
|    PR0012982|     2026-05-07|    PL02|     MC009|     OP0405|Evening|     CTL-330|   Controllers|         1194|          1237|              4|               0|    275.64|        68.43|          5.18|          Pass|              No|    Bharat|         5|
|    PR0082579|     2026-01-20|    PL03|     MC013|     OP0313|Morning|     MTR-100|        Motors|         1200|          1243|              1|              40|    517.17|        51.05|          3.65|        Rework|              No|    Charan|         1|
|    PR0030298|     2026-05-04|    PL03|     MC011|     OP0514|  Night|     CTL-130|   Controllers|         1195|          1239|             30|              74|    616.84|        60.83|          5.16|          Pass|              No|    Harini|         2|
|    PR0117602|     2026-02-13|    PL03|     MC012|     OP0368|Evening|     MTR-100|        Motors|         1197|          1239|             27|              38|    521.93|        69.64|          2.28|          Pass|              No|    Bharat|         3|
|    PR0102987|     2026-07-07|    PL03|     MC015|     OP0220|Morning|     PMP-310|         Pumps|         1192|          1236|             10|               1|    304.23|        71.75|          3.49|          Pass|              No|     Farah|         4|
|    PR0021534|     2026-06-14|    PL03|     MC011|     OP0042|  Night|     MTR-100|        Motors|         1189|          1235|             46|              53|    507.11|        60.86|          1.71|          Pass|             Yes|    Charan|         5|
|    PR0008535|     2026-02-23|    PL04|     MC018|     OP0286|Morning|     MTR-200|        Motors|         1199|          1245|              0|              53|    257.72|        60.24|           2.6|          Pass|              No|     Farah|         1|
|    PR0087560|     2026-06-29|    PL04|     MC018|     OP0587|  Night|     VLV-120|        Valves|         1199|          1245|             60|               0|    500.87|        58.11|          3.58|          Pass|             Yes|    Charan|         2|
|    PR0047939|     2026-09-28|    PL04|     MC020|     OP0174|Evening|     PMP-210|         Pumps|         1199|          1243|             42|              28|    502.25|        66.71|          2.97|          Pass|              No|     Anita|         3|
|    PR0069661|     2026-01-28|    PL04|     MC020|     OP0499|Evening|     CTL-130|   Controllers|         1200|          1242|             13|              40|     392.3|         NULL|           2.7|          Pass|             Yes|     Irfan|         4|
|    PR0093782|     2026-06-01|    PL04|     MC020|     OP0240|Evening|     VLV-320|        Valves|         1192|          1239|             10|               0|    257.87|         62.6|          4.35|        Rework|              No|     Anita|         5|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----------+
only showing top 20 rows

In [151]:
df_machine_output = df.groupBy("plant_id","machine_id").agg(sum("units_produced").alias("total_output"))

window_machine = Window.partitionBy("plant_id").orderBy(col("total_output").desc())

df_top_machines = df_machine_output.withColumn("machine_rank",dense_rank().over(window_machine)).filter(col("machine_rank") <= 3)

df_top_machines.show()

+--------+----------+------------+------------+
|plant_id|machine_id|total_output|machine_rank|
+--------+----------+------------+------------+
|    PL01|     MC004|     2722412|           1|
|    PL01|     MC002|     2713779|           2|
|    PL01|     MC001|     2691431|           3|
|    PL02|     MC009|     2760070|           1|
|    PL02|     MC007|     2713038|           2|
|    PL02|     MC008|     2705850|           3|
|    PL03|     MC012|     2750570|           1|
|    PL03|     MC015|     2739284|           2|
|    PL03|     MC014|     2735500|           3|
|    PL04|     MC016|     2750780|           1|
|    PL04|     MC019|     2735839|           2|
|    PL04|     MC017|     2726300|           3|
|    PL05|     MC024|     2737331|           1|
|    PL05|     MC023|     2718075|           2|
|    PL05|     MC022|     2635629|           3|
|    PL06|     MC026|     2723306|           1|
|    PL06|     MC027|     2718877|           2|
|    PL06|     MC030|     2701993|           3|
+--------+----------+------------+------------+

In [152]:
window_plant_all = Window.partitionBy("plant_id")

df_plant_total = df.withColumn("total_plant_production",sum("units_produced").over(window_plant_all))

df_plant_total.select("plant_id","production_id","units_produced","total_plant_production").show()

+--------+-------------+--------------+----------------------+
|plant_id|production_id|units_produced|total_plant_production|
+--------+-------------+--------------+----------------------+
|    PL01|    PR0000003|           380|              13488232|
|    PL01|    PR0000006|           795|              13488232|
|    PL01|    PR0000019|           380|              13488232|
|    PL01|    PR0000026|           663|              13488232|
|    PL01|    PR0000028|          1042|              13488232|
|    PL01|    PR0000030|           359|              13488232|
|    PL01|    PR0000031|           776|              13488232|
|    PL01|    PR0000039|           265|              13488232|
|    PL01|    PR0000040|           306|              13488232|
|    PL01|    PR0000050|           908|              13488232|
|    PL01|    PR0000055|           478|              13488232|
|    PL01|    PR0000057|           325|              13488232|
|    PL01|    PR0000063|           665|              13488232|
|    PL01|    PR0000080|           821|              13488232|
|    PL01|    PR0000088|           676|              13488232|
|    PL01|    PR0000090|           222|              13488232|
|    PL01|    PR0000095|           307|              13488232|
|    PL01|    PR0000097|           264|              13488232|
|    PL01|    PR0000098|           579|              13488232|
|    PL01|    PR0000102|           445|              13488232|
+--------+-------------+--------------+----------------------+
only showing top 20 rows

In [153]:
window_machine_all = Window.partitionBy("machine_id")

df_machine_avg = df.withColumn("average_machine_output",avg("units_produced").over(window_machine_all))

df_machine_avg.select("machine_id","production_id","units_produced","average_machine_output").show()

+----------+-------------+--------------+----------------------+
|machine_id|production_id|units_produced|average_machine_output|
+----------+-------------+--------------+----------------------+
|     MC001|    PR0000026|           663|     671.5147205588822|
|     MC001|    PR0000057|           325|     671.5147205588822|
|     MC001|    PR0000088|           676|     671.5147205588822|
|     MC001|    PR0000135|           375|     671.5147205588822|
|     MC001|    PR0000139|           378|     671.5147205588822|
|     MC001|    PR0000159|           762|     671.5147205588822|
|     MC001|    PR0000216|           431|     671.5147205588822|
|     MC001|    PR0000232|          1030|     671.5147205588822|
|     MC001|    PR0000243|           464|     671.5147205588822|
|     MC001|    PR0000279|           616|     671.5147205588822|
|     MC001|    PR0000344|           433|     671.5147205588822|
|     MC001|    PR0000354|           305|     671.5147205588822|
|     MC001|    PR0000410|           991|     671.5147205588822|
|     MC001|    PR0000415|          1002|     671.5147205588822|
|     MC001|    PR0000431|           574|     671.5147205588822|
|     MC001|    PR0000452|           559|     671.5147205588822|
|     MC001|    PR0000477|          1160|     671.5147205588822|
|     MC001|    PR0000485|           695|     671.5147205588822|
|     MC001|    PR0000502|           350|     671.5147205588822|
|     MC001|    PR0000503|           551|     671.5147205588822|
+----------+-------------+--------------+----------------------+
only showing top 20 rows

In [154]:
window_cumulative = Window.partitionBy("machine_id").orderBy("production_date").rowsBetween(Window.unboundedPreceding,Window.currentRow)

df_cumulative = df.withColumn("cumulative_production",sum("units_produced").over(window_cumulative))

df_cumulative.select("machine_id","production_date","units_produced","cumulative_production").show()

+----------+---------------+--------------+---------------------+
|machine_id|production_date|units_produced|cumulative_production|
+----------+---------------+--------------+---------------------+
|     MC001|     2026-01-01|           437|                  437|
|     MC001|     2026-01-01|           997|                 1434|
|     MC001|     2026-01-01|           822|                 2256|
|     MC001|     2026-01-01|           817|                 3073|
|     MC001|     2026-01-01|           784|                 3857|
|     MC001|     2026-01-01|           472|                 4329|
|     MC001|     2026-01-01|          1078|                 5407|
|     MC001|     2026-01-01|          1027|                 6434|
|     MC001|     2026-01-01|          1023|                 7457|
|     MC001|     2026-01-01|           257|                 7714|
|     MC001|     2026-01-01|           929|                 8643|
|     MC001|     2026-01-01|           926|                 9569|
|     MC001|     2026-01-01|           799|                10368|
|     MC001|     2026-01-01|           560|                10928|
|     MC001|     2026-01-01|          1157|                12085|
|     MC001|     2026-01-01|           536|                12621|
|     MC001|     2026-01-02|           519|                13140|
|     MC001|     2026-01-02|           487|                13627|
|     MC001|     2026-01-02|           611|                14238|
|     MC001|     2026-01-02|           952|                15190|
+----------+---------------+--------------+---------------------+
only showing top 20 rows

In [155]:
window_date = Window.partitionBy("machine_id").orderBy("production_date")

df_lag = df.withColumn("previous_output",lag("units_produced", 1).over(window_date))

df_lag.select("machine_id","production_date","units_produced","previous_output").show()

+----------+---------------+--------------+---------------+
|machine_id|production_date|units_produced|previous_output|
+----------+---------------+--------------+---------------+
|     MC001|     2026-01-01|           437|           NULL|
|     MC001|     2026-01-01|           997|            437|
|     MC001|     2026-01-01|           822|            997|
|     MC001|     2026-01-01|           817|            822|
|     MC001|     2026-01-01|           784|            817|
|     MC001|     2026-01-01|           472|            784|
|     MC001|     2026-01-01|          1078|            472|
|     MC001|     2026-01-01|          1027|           1078|
|     MC001|     2026-01-01|          1023|           1027|
|     MC001|     2026-01-01|           257|           1023|
|     MC001|     2026-01-01|           929|            257|
|     MC001|     2026-01-01|           926|            929|
|     MC001|     2026-01-01|           799|            926|
|     MC001|     2026-01-01|           560|            799|
|     MC001|     2026-01-01|          1157|            560|
|     MC001|     2026-01-01|           536|           1157|
|     MC001|     2026-01-02|           519|            536|
|     MC001|     2026-01-02|           487|            519|
|     MC001|     2026-01-02|           611|            487|
|     MC001|     2026-01-02|           952|            611|
+----------+---------------+--------------+---------------+
only showing top 20 rows

In [156]:
df_lead = df.withColumn("next_output",lead("units_produced", 1).over(window_date))

df_lead.select("machine_id","production_date","units_produced","next_output").show()

+----------+---------------+--------------+-----------+
|machine_id|production_date|units_produced|next_output|
+----------+---------------+--------------+-----------+
|     MC001|     2026-01-01|           437|        997|
|     MC001|     2026-01-01|           997|        822|
|     MC001|     2026-01-01|           822|        817|
|     MC001|     2026-01-01|           817|        784|
|     MC001|     2026-01-01|           784|        472|
|     MC001|     2026-01-01|           472|       1078|
|     MC001|     2026-01-01|          1078|       1027|
|     MC001|     2026-01-01|          1027|       1023|
|     MC001|     2026-01-01|          1023|        257|
|     MC001|     2026-01-01|           257|        929|
|     MC001|     2026-01-01|           929|        926|
|     MC001|     2026-01-01|           926|        799|
|     MC001|     2026-01-01|           799|        560|
|     MC001|     2026-01-01|           560|       1157|
|     MC001|     2026-01-01|          1157|        536|
|     MC001|     2026-01-01|           536|        519|
|     MC001|     2026-01-02|           519|        487|
|     MC001|     2026-01-02|           487|        611|
|     MC001|     2026-01-02|           611|        952|
|     MC001|     2026-01-02|           952|        485|
+----------+---------------+--------------+-----------+
only showing top 20 rows

In [157]:
df_change = df.withColumn("previous_output",lag("units_produced", 1).over(window_date))

df_change = df_change.withColumn("output_change",col("units_produced") - col("previous_output"))

df_change.select("machine_id","production_date","units_produced","previous_output","output_change").show()

+----------+---------------+--------------+---------------+-------------+
|machine_id|production_date|units_produced|previous_output|output_change|
+----------+---------------+--------------+---------------+-------------+
|     MC001|     2026-01-01|           437|           NULL|         NULL|
|     MC001|     2026-01-01|           997|            437|          560|
|     MC001|     2026-01-01|           822|            997|         -175|
|     MC001|     2026-01-01|           817|            822|           -5|
|     MC001|     2026-01-01|           784|            817|          -33|
|     MC001|     2026-01-01|           472|            784|         -312|
|     MC001|     2026-01-01|          1078|            472|          606|
|     MC001|     2026-01-01|          1027|           1078|          -51|
|     MC001|     2026-01-01|          1023|           1027|           -4|
|     MC001|     2026-01-01|           257|           1023|         -766|
|     MC001|     2026-01-01|           929|            257|          672|
|     MC001|     2026-01-01|           926|            929|           -3|
|     MC001|     2026-01-01|           799|            926|         -127|
|     MC001|     2026-01-01|           560|            799|         -239|
|     MC001|     2026-01-01|          1157|            560|          597|
|     MC001|     2026-01-01|           536|           1157|         -621|
|     MC001|     2026-01-02|           519|            536|          -17|
|     MC001|     2026-01-02|           487|            519|          -32|
|     MC001|     2026-01-02|           611|            487|          124|
|     MC001|     2026-01-02|           952|            611|          341|
+----------+---------------+--------------+---------------+-------------+
only showing top 20 rows

In [158]:
df_family_output = df.groupBy("product_family").agg(sum("units_produced").alias("total_output"))

window_family = Window.orderBy(col("total_output").desc())

df_family_rank = df_family_output.withColumn("family_rank",dense_rank().over(window_family))

df_family_rank.show()

+--------------+------------+-----------+
|product_family|total_output|family_rank|
+--------------+------------+-----------+
|        Valves|    20433082|          1|
|         Pumps|    20208739|          2|
|   Controllers|    20168572|          3|
|        Motors|    20117495|          4|
+--------------+------------+-----------+

Date and Time Functions:

1. Convert to DateType .
2. Extract year.
3. Extract month.
4. Extract day.
5. Extract month name.
6. Extract day name.
7. Create year_month .
8. Calculate monthly production.
9. Calculate monthly defects.
10. Calculate production by month and plant.
11. Find production between two dates.
12. Add 7 days to production date.
13. Subtract 30 days.
14. Calculate difference from current date.
15. Find the month with the highest total output.

In [159]:
from pyspark.sql.functions import (
    to_date, year, month, dayofmonth, date_format,
    sum, col, desc, date_add, date_sub, datediff, current_date
)
base_df = spark.read.csv("manufacturing_production_120k.csv", header=True, inferSchema=True)

In [160]:
df = base_df.withColumn("production_date", to_date(col("production_date")))
df.select("production_date").printSchema()

root
 |-- production_date: date (nullable = true)

In [161]:
df.select("production_date", year("production_date").alias("year")).show(5)

+---------------+----+
|production_date|year|
+---------------+----+
|     2026-08-07|2026|
|     2026-08-03|2026|
|     2026-05-20|2026|
|     2026-01-15|2026|
|     2026-09-21|2026|
+---------------+----+
only showing top 5 rows

In [162]:
df.select("production_date", month("production_date").alias("month")).show(5)

+---------------+-----+
|production_date|month|
+---------------+-----+
|     2026-08-07|    8|
|     2026-08-03|    8|
|     2026-05-20|    5|
|     2026-01-15|    1|
|     2026-09-21|    9|
+---------------+-----+
only showing top 5 rows

In [163]:
df.select("production_date", dayofmonth("production_date").alias("day")).show(5)

+---------------+---+
|production_date|day|
+---------------+---+
|     2026-08-07|  7|
|     2026-08-03|  3|
|     2026-05-20| 20|
|     2026-01-15| 15|
|     2026-09-21| 21|
+---------------+---+
only showing top 5 rows

In [164]:
df.select("production_date", date_format("production_date", "MMMM").alias("month_name")).show(5)

+---------------+----------+
|production_date|month_name|
+---------------+----------+
|     2026-08-07|    August|
|     2026-08-03|    August|
|     2026-05-20|       May|
|     2026-01-15|   January|
|     2026-09-21| September|
+---------------+----------+
only showing top 5 rows

In [165]:
df.select("production_date", date_format("production_date", "EEEE").alias("day_name")).show(5)

+---------------+---------+
|production_date| day_name|
+---------------+---------+
|     2026-08-07|   Friday|
|     2026-08-03|   Monday|
|     2026-05-20|Wednesday|
|     2026-01-15| Thursday|
|     2026-09-21|   Monday|
+---------------+---------+
only showing top 5 rows

In [166]:
df = df.withColumn("year_month", date_format("production_date", "yyyy-MM"))
df.select("production_date", "year_month").show(5)

+---------------+----------+
|production_date|year_month|
+---------------+----------+
|     2026-08-07|   2026-08|
|     2026-08-03|   2026-08|
|     2026-05-20|   2026-05|
|     2026-01-15|   2026-01|
|     2026-09-21|   2026-09|
+---------------+----------+
only showing top 5 rows

In [167]:
df.groupBy("year_month").agg(sum("units_produced").alias("monthly_production")).orderBy("year_month").show()

+----------+------------------+
|year_month|monthly_production|
+----------+------------------+
|   2026-01|           8478059|
|   2026-02|           7810891|
|   2026-03|           8441121|
|   2026-04|           8211005|
|   2026-05|           8507542|
|   2026-06|           8400505|
|   2026-07|           8476416|
|   2026-08|           8529150|
|   2026-09|           8115221|
|   2026-10|           5957978|
+----------+------------------+

In [168]:
df.groupBy("year_month").agg(sum("defective_units").alias("monthly_defects")).orderBy("year_month").show()

+----------+---------------+
|year_month|monthly_defects|
+----------+---------------+
|   2026-01|         211741|
|   2026-02|         197462|
|   2026-03|         212036|
|   2026-04|         208707|
|   2026-05|         212049|
|   2026-06|         210381|
|   2026-07|         210482|
|   2026-08|         214807|
|   2026-09|         202990|
|   2026-10|         149589|
+----------+---------------+

In [169]:
df.groupBy("year_month", "plant_id").agg(sum("units_produced").alias("total_units")).orderBy("year_month", "plant_id").show()

+----------+--------+-----------+
|year_month|plant_id|total_units|
+----------+--------+-----------+
|   2026-01|    PL01|    1451436|
|   2026-01|    PL02|    1419252|
|   2026-01|    PL03|    1429811|
|   2026-01|    PL04|    1399488|
|   2026-01|    PL05|    1375887|
|   2026-01|    PL06|    1402185|
|   2026-02|    PL01|    1342273|
|   2026-02|    PL02|    1278581|
|   2026-02|    PL03|    1305531|
|   2026-02|    PL04|    1292557|
|   2026-02|    PL05|    1324271|
|   2026-02|    PL06|    1267678|
|   2026-03|    PL01|    1442140|
|   2026-03|    PL02|    1359740|
|   2026-03|    PL03|    1416484|
|   2026-03|    PL04|    1447603|
|   2026-03|    PL05|    1411435|
|   2026-03|    PL06|    1363719|
|   2026-04|    PL01|    1350450|
|   2026-04|    PL02|    1369684|
+----------+--------+-----------+
only showing top 20 rows

In [170]:
df.filter(col("production_date").between("2023-01-01", "2023-03-31")).show(5)

+-------------+---------------+--------+----------+-----------+-----+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|year_month|
+-------------+---------------+--------+----------+-----------+-----+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----------+
+-------------+---------------+--------+----------+-----------+-----+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----------+

In [171]:
df.select("production_date", date_add("production_date", 7).alias("plus_7_days")).show(5)

+---------------+-----------+
|production_date|plus_7_days|
+---------------+-----------+
|     2026-08-07| 2026-08-14|
|     2026-08-03| 2026-08-10|
|     2026-05-20| 2026-05-27|
|     2026-01-15| 2026-01-22|
|     2026-09-21| 2026-09-28|
+---------------+-----------+
only showing top 5 rows

In [172]:
df.select("production_date", date_sub("production_date", 30).alias("minus_30_days")).show(5)

+---------------+-------------+
|production_date|minus_30_days|
+---------------+-------------+
|     2026-08-07|   2026-07-08|
|     2026-08-03|   2026-07-04|
|     2026-05-20|   2026-04-20|
|     2026-01-15|   2025-12-16|
|     2026-09-21|   2026-08-22|
+---------------+-------------+
only showing top 5 rows

In [173]:
df.select("production_date", datediff(current_date(), col("production_date")).alias("days_ago")).show(5)

+---------------+--------+
|production_date|days_ago|
+---------------+--------+
|     2026-08-07|      80|
|     2026-08-03|      84|
|     2026-05-20|     159|
|     2026-01-15|     284|
|     2026-09-21|      35|
+---------------+--------+
only showing top 5 rows

In [174]:
df.groupBy("year_month").agg(sum("units_produced").alias("total_output")).orderBy(desc("total_output")).limit(1).show()

+----------+------------+
|year_month|total_output|
+----------+------------+
|   2026-08|     8529150|
+----------+------------+